// src/app.ts
import cookieParser from "cookie-parser";
import cors from "cors";
import express11 from "express";

// src/config/index.ts
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
var config_default = {
  port: process.env.PORT,
  database_url: process.env.DATABASE_URL,
  app_url: process.env.APP_URL,
  env: process.env.NODE_ENV,
  bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
  jwt_access_secret: process.env.JWT_ACCESS_SECRET,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET,
  jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN,
  jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN,
  // 👈 এটা যোগ করো
  ssl: {
    store_id: process.env.SSL_STORE_ID,
    store_passwd: process.env.SSL_STORE_PASSWORD,
    is_live: process.env.SSL_IS_LIVE === "true",
    success_url: process.env.SSL_SUCCESS_URL,
    fail_url: process.env.SSL_FAIL_URL,
    cancel_url: process.env.SSL_CANCEL_URL
  },
  frontend_url: process.env.FRONTEND_URL
};

// src/modules/user/user.routes.ts
import express from "express";

// src/modules/user/user.controller.ts
import httpStatus from "http-status";

// src/utils/catchAsync.ts
var catchAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      next(error);
    }
  };
};

// src/utils/sendResponse.ts
var sendResponse = (res, data) => {
  res.status(data.statusCode).json({
    success: data.success,
    statusCode: data.statusCode,
    message: data.message,
    data: data.data,
    meta: data.meta
  });
};

// src/modules/user/user.service.ts
import bcrypt from "bcryptjs";

// src/lib/prisma.ts
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

// generated/prisma/client.ts
import * as path2 from "node:path";
import { fileURLToPath } from "node:url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.8.0",
  "engineVersion": "3c6e192761c0362d496ed980de936e2f3cebcd3a",
  "activeProvider": "postgresql",
  "inlineSchema": 'model Booking {\n  id           String        @id @default(uuid())\n  customerId   String\n  serviceId    String\n  technicianId String\n  status       BookingStatus @default(REQUESTED)\n  scheduledAt  DateTime\n  address      String\n  note         String?\n  price        Float\n  createdAt    DateTime      @default(now())\n  updatedAt    DateTime      @updatedAt\n\n  // Relationships\n  customer   User              @relation(fields: [customerId], references: [id])\n  service    Service           @relation(fields: [serviceId], references: [id])\n  technician TechnicianProfile @relation(fields: [technicianId], references: [id])\n  payment    Payment?\n  review     Review?\n\n  @@map("bookings")\n}\n\nenum UserRole {\n  CUSTOMER\n  TECHNICIAN\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANNED\n}\n\nenum BookingStatus {\n  REQUESTED\n  ACCEPTED\n  DECLINED\n  PAID\n  IN_PROGRESS\n  COMPLETED\n  CANCELLED\n}\n\n// sss\n\nenum PaymentStatus {\n  PENDING\n  COMPLETED\n  FAILED\n}\n\nenum PaymentMethod {\n  SSLCOMMERZ\n  STRIPE\n}\n\nmodel Payment {\n  id            String        @id @default(uuid())\n  bookingId     String        @unique\n  transactionId String        @unique\n  amount        Float\n  method        PaymentMethod @default(SSLCOMMERZ)\n  status        PaymentStatus @default(PENDING)\n  paidAt        DateTime?\n  createdAt     DateTime      @default(now())\n  updatedAt     DateTime      @updatedAt\n\n  // Relationships\n  booking Booking @relation(fields: [bookingId], references: [id])\n\n  @@map("payments")\n}\n\nmodel Review {\n  id           String   @id @default(uuid())\n  bookingId    String   @unique\n  customerId   String\n  technicianId String\n  rating       Int // 1 \u09A5\u09C7\u0995\u09C7 5\n  comment      String?\n  createdAt    DateTime @default(now())\n  updatedAt    DateTime @updatedAt\n\n  // Relationships\n  booking    Booking           @relation(fields: [bookingId], references: [id])\n  customer   User              @relation(fields: [customerId], references: [id])\n  technician TechnicianProfile @relation(fields: [technicianId], references: [id])\n\n  @@map("reviews")\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Get a free hosted Postgres database in seconds: `npx create-db`\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel Category {\n  id          String   @id @default(uuid())\n  name        String   @unique\n  description String?\n  createdAt   DateTime @default(now())\n  updatedAt   DateTime @updatedAt\n\n  // Relationships\n  services Service[]\n\n  @@map("categories")\n}\n\nmodel Service {\n  id           String   @id @default(uuid())\n  title        String\n  description  String?\n  price        Float\n  durationMins Int?\n  categoryId   String\n  technicianId String\n  createdAt    DateTime @default(now())\n  updatedAt    DateTime @updatedAt\n\n  // Relationships\n  category   Category          @relation(fields: [categoryId], references: [id])\n  technician TechnicianProfile @relation(fields: [technicianId], references: [id], onDelete: Cascade)\n  bookings   Booking[]\n\n  @@map("services")\n}\n\nmodel TechnicianProfile {\n  id           String    @id @default(uuid())\n  userId       String    @unique\n  bio          String?\n  experience   Int       @default(0) // years of experience\n  skills       String[]\n  hourlyRate   Float\n  isAvailable  Boolean   @default(true)\n  ratingAvg    Float     @default(0)\n  totalReviews Int       @default(0)\n  location     String?\n  createdAt    DateTime  @default(now())\n  updatedAt    DateTime  @updatedAt\n  services     Service[]\n  // Relationships\n  user         User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  bookings     Booking[]\n  reviews      Review[]\n\n  @@map("technician_profiles")\n}\n\nmodel User {\n  id                String             @id @default(uuid())\n  name              String\n  email             String             @unique\n  password          String\n  role              UserRole           @default(CUSTOMER)\n  status            UserStatus         @default(ACTIVE)\n  createdAt         DateTime           @default(now())\n  updatedAt         DateTime           @updatedAt\n  technicianProfile TechnicianProfile?\n  bookings          Booking[]\n  reviews           Review[]\n\n  @@map("users")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"serviceId","kind":"scalar","type":"String"},{"name":"technicianId","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"scheduledAt","kind":"scalar","type":"DateTime"},{"name":"address","kind":"scalar","type":"String"},{"name":"note","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"customer","kind":"object","type":"User","relationName":"BookingToUser"},{"name":"service","kind":"object","type":"Service","relationName":"BookingToService"},{"name":"technician","kind":"object","type":"TechnicianProfile","relationName":"BookingToTechnicianProfile"},{"name":"payment","kind":"object","type":"Payment","relationName":"BookingToPayment"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"}],"dbName":"bookings"},"Payment":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"transactionId","kind":"scalar","type":"String"},{"name":"amount","kind":"scalar","type":"Float"},{"name":"method","kind":"enum","type":"PaymentMethod"},{"name":"status","kind":"enum","type":"PaymentStatus"},{"name":"paidAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToPayment"}],"dbName":"payments"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"customerId","kind":"scalar","type":"String"},{"name":"technicianId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"},{"name":"customer","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"technician","kind":"object","type":"TechnicianProfile","relationName":"ReviewToTechnicianProfile"}],"dbName":"reviews"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"services","kind":"object","type":"Service","relationName":"CategoryToService"}],"dbName":"categories"},"Service":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"durationMins","kind":"scalar","type":"Int"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"technicianId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToService"},{"name":"technician","kind":"object","type":"TechnicianProfile","relationName":"ServiceToTechnicianProfile"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToService"}],"dbName":"services"},"TechnicianProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"experience","kind":"scalar","type":"Int"},{"name":"skills","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"isAvailable","kind":"scalar","type":"Boolean"},{"name":"ratingAvg","kind":"scalar","type":"Float"},{"name":"totalReviews","kind":"scalar","type":"Int"},{"name":"location","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"services","kind":"object","type":"Service","relationName":"ServiceToTechnicianProfile"},{"name":"user","kind":"object","type":"User","relationName":"TechnicianProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToTechnicianProfile"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTechnicianProfile"}],"dbName":"technician_profiles"},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"UserRole"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"technicianProfile","kind":"object","type":"TechnicianProfile","relationName":"TechnicianProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"}],"dbName":"users"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","services","_count","category","technician","bookings","user","booking","customer","reviews","technicianProfile","service","payment","review","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","data","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","create","update","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","having","_avg","_sum","_min","_max","Booking.groupBy","Booking.aggregate","Payment.findUnique","Payment.findUniqueOrThrow","Payment.findFirst","Payment.findFirstOrThrow","Payment.findMany","Payment.createOne","Payment.createMany","Payment.createManyAndReturn","Payment.updateOne","Payment.updateMany","Payment.updateManyAndReturn","Payment.upsertOne","Payment.deleteOne","Payment.deleteMany","Payment.groupBy","Payment.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Service.findUnique","Service.findUniqueOrThrow","Service.findFirst","Service.findFirstOrThrow","Service.findMany","Service.createOne","Service.createMany","Service.createManyAndReturn","Service.updateOne","Service.updateMany","Service.updateManyAndReturn","Service.upsertOne","Service.deleteOne","Service.deleteMany","Service.groupBy","Service.aggregate","TechnicianProfile.findUnique","TechnicianProfile.findUniqueOrThrow","TechnicianProfile.findFirst","TechnicianProfile.findFirstOrThrow","TechnicianProfile.findMany","TechnicianProfile.createOne","TechnicianProfile.createMany","TechnicianProfile.createManyAndReturn","TechnicianProfile.updateOne","TechnicianProfile.updateMany","TechnicianProfile.updateManyAndReturn","TechnicianProfile.upsertOne","TechnicianProfile.deleteOne","TechnicianProfile.deleteMany","TechnicianProfile.groupBy","TechnicianProfile.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","AND","OR","NOT","id","name","email","password","UserRole","role","UserStatus","status","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","every","some","none","userId","bio","experience","skills","hourlyRate","isAvailable","ratingAvg","totalReviews","location","has","hasEvery","hasSome","title","description","price","durationMins","categoryId","technicianId","bookingId","customerId","rating","comment","transactionId","amount","PaymentMethod","method","PaymentStatus","paidAt","serviceId","BookingStatus","scheduledAt","address","note","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide","push"]'),
  graph: "gARHcBMGAACHAgAgCgAA6wEAIA0AAIoCACAOAACLAgAgDwAAjAIAIIgBAACIAgAwiQEAAAsAEIoBAACIAgAwiwEBAAAAAZIBAACJAsEBIpMBQADTAQAhlAFAANMBACGxAQgA6AEAIbQBAQDQAQAhtgEBANABACG_AQEA0AEAIcEBQADTAQAhwgEBANABACHDAQEA5gEAIQEAAAABACATAwAA6gEAIAcAANUBACAIAADrAQAgCwAA1gEAIIgBAADlAQAwiQEAAAMAEIoBAADlAQAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhowEBANABACGkAQEA5gEAIaUBAgDnAQAhpgEAANoBACCnAQgA6AEAIagBIADpAQAhqQEIAOgBACGqAQIA5wEAIasBAQDmAQAhAQAAAAMAIA8FAACPAgAgBgAAhwIAIAcAANUBACCIAQAAjQIAMIkBAAAFABCKAQAAjQIAMIsBAQDQAQAhkwFAANMBACGUAUAA0wEAIa8BAQDQAQAhsAEBAOYBACGxAQgA6AEAIbIBAgCOAgAhswEBANABACG0AQEA0AEAIQUFAADHAwAgBgAAkAMAIAcAAJEDACCwAQAAkwMAILIBAACTAwAgDwUAAI8CACAGAACHAgAgBwAA1QEAIIgBAACNAgAwiQEAAAUAEIoBAACNAgAwiwEBAAAAAZMBQADTAQAhlAFAANMBACGvAQEA0AEAIbABAQDmAQAhsQEIAOgBACGyAQIAjgIAIbMBAQDQAQAhtAEBANABACEDAAAABQAgAQAABgAwAgAABwAgAwAAAAUAIAEAAAYAMAIAAAcAIAEAAAAFACATBgAAhwIAIAoAAOsBACANAACKAgAgDgAAiwIAIA8AAIwCACCIAQAAiAIAMIkBAAALABCKAQAAiAIAMIsBAQDQAQAhkgEAAIkCwQEikwFAANMBACGUAUAA0wEAIbEBCADoAQAhtAEBANABACG2AQEA0AEAIb8BAQDQAQAhwQFAANMBACHCAQEA0AEAIcMBAQDmAQAhBgYAAJADACAKAACcAwAgDQAAxAMAIA4AAMUDACAPAADGAwAgwwEAAJMDACADAAAACwAgAQAADAAwAgAAAQAgAQAAAAsAIAMAAAALACABAAAMADACAAABACAOBgAAhwIAIAkAAIECACAKAADrAQAgiAEAAIYCADCJAQAAEAAQigEAAIYCADCLAQEA0AEAIZMBQADTAQAhlAFAANMBACG0AQEA0AEAIbUBAQDQAQAhtgEBANABACG3AQIA5wEAIbgBAQDmAQAhBAYAAJADACAJAAC-AwAgCgAAnAMAILgBAACTAwAgDgYAAIcCACAJAACBAgAgCgAA6wEAIIgBAACGAgAwiQEAABAAEIoBAACGAgAwiwEBAAAAAZMBQADTAQAhlAFAANMBACG0AQEA0AEAIbUBAQAAAAG2AQEA0AEAIbcBAgDnAQAhuAEBAOYBACEDAAAAEAAgAQAAEQAwAgAAEgAgAQAAAAUAIAEAAAALACABAAAAEAAgAwAAAAsAIAEAAAwAMAIAAAEAIAMAAAAQACABAAARADACAAASACABAAAACwAgAQAAABAAIA0JAACBAgAgiAEAAP0BADCJAQAAGwAQigEAAP0BADCLAQEA0AEAIZIBAAD_Ab4BIpMBQADTAQAhlAFAANMBACG1AQEA0AEAIbkBAQDQAQAhugEIAOgBACG8AQAA_gG8ASK-AUAAgAIAIQEAAAAbACABAAAAEAAgAQAAAAEAIAMAAAALACABAAAMADACAAABACADAAAACwAgAQAADAAwAgAAAQAgAwAAAAsAIAEAAAwAMAIAAAEAIBAGAADOAgAgCgAA7gIAIA0AAM0CACAOAADPAgAgDwAA0AIAIIsBAQAAAAGSAQAAAMEBApMBQAAAAAGUAUAAAAABsQEIAAAAAbQBAQAAAAG2AQEAAAABvwEBAAAAAcEBQAAAAAHCAQEAAAABwwEBAAAAAQEVAAAiACALiwEBAAAAAZIBAAAAwQECkwFAAAAAAZQBQAAAAAGxAQgAAAABtAEBAAAAAbYBAQAAAAG_AQEAAAABwQFAAAAAAcIBAQAAAAHDAQEAAAABARUAACQAMAEVAAAkADAQBgAAugIAIAoAAOwCACANAAC5AgAgDgAAuwIAIA8AALwCACCLAQEAkwIAIZIBAAC2AsEBIpMBQACWAgAhlAFAAJYCACGxAQgAtwIAIbQBAQCTAgAhtgEBAJMCACG_AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQIAAAABACAVAAAnACALiwEBAJMCACGSAQAAtgLBASKTAUAAlgIAIZQBQACWAgAhsQEIALcCACG0AQEAkwIAIbYBAQCTAgAhvwEBAJMCACHBAUAAlgIAIcIBAQCTAgAhwwEBAKUCACECAAAACwAgFQAAKQAgAgAAAAsAIBUAACkAIAMAAAABACAcAAAiACAdAAAnACABAAAAAQAgAQAAAAsAIAYEAAC_AwAgIgAAwAMAICMAAMMDACAkAADCAwAgJQAAwQMAIMMBAACTAwAgDogBAACCAgAwiQEAADAAEIoBAACCAgAwiwEBAMIBACGSAQAAgwLBASKTAUAAxQEAIZQBQADFAQAhsQEIANsBACG0AQEAwgEAIbYBAQDCAQAhvwEBAMIBACHBAUAAxQEAIcIBAQDCAQAhwwEBANgBACEDAAAACwAgAQAALwAwIQAAMAAgAwAAAAsAIAEAAAwAMAIAAAEAIA0JAACBAgAgiAEAAP0BADCJAQAAGwAQigEAAP0BADCLAQEAAAABkgEAAP8BvgEikwFAANMBACGUAUAA0wEAIbUBAQAAAAG5AQEAAAABugEIAOgBACG8AQAA_gG8ASK-AUAAgAIAIQEAAAAzACABAAAAMwAgAgkAAL4DACC-AQAAkwMAIAMAAAAbACABAAA2ADACAAAzACADAAAAGwAgAQAANgAwAgAAMwAgAwAAABsAIAEAADYAMAIAADMAIAoJAAC9AwAgiwEBAAAAAZIBAAAAvgECkwFAAAAAAZQBQAAAAAG1AQEAAAABuQEBAAAAAboBCAAAAAG8AQAAALwBAr4BQAAAAAEBFQAAOgAgCYsBAQAAAAGSAQAAAL4BApMBQAAAAAGUAUAAAAABtQEBAAAAAbkBAQAAAAG6AQgAAAABvAEAAAC8AQK-AUAAAAABARUAADwAMAEVAAA8ADAKCQAAvAMAIIsBAQCTAgAhkgEAAMoCvgEikwFAAJYCACGUAUAAlgIAIbUBAQCTAgAhuQEBAJMCACG6AQgAtwIAIbwBAADJArwBIr4BQADLAgAhAgAAADMAIBUAAD8AIAmLAQEAkwIAIZIBAADKAr4BIpMBQACWAgAhlAFAAJYCACG1AQEAkwIAIbkBAQCTAgAhugEIALcCACG8AQAAyQK8ASK-AUAAywIAIQIAAAAbACAVAABBACACAAAAGwAgFQAAQQAgAwAAADMAIBwAADoAIB0AAD8AIAEAAAAzACABAAAAGwAgBgQAALcDACAiAAC4AwAgIwAAuwMAICQAALoDACAlAAC5AwAgvgEAAJMDACAMiAEAAPMBADCJAQAASAAQigEAAPMBADCLAQEAwgEAIZIBAAD1Ab4BIpMBQADFAQAhlAFAAMUBACG1AQEAwgEAIbkBAQDCAQAhugEIANsBACG8AQAA9AG8ASK-AUAA9gEAIQMAAAAbACABAABHADAhAABIACADAAAAGwAgAQAANgAwAgAAMwAgAQAAABIAIAEAAAASACADAAAAEAAgAQAAEQAwAgAAEgAgAwAAABAAIAEAABEAMAIAABIAIAMAAAAQACABAAARADACAAASACALBgAAqwIAIAkAAKoCACAKAADDAgAgiwEBAAAAAZMBQAAAAAGUAUAAAAABtAEBAAAAAbUBAQAAAAG2AQEAAAABtwECAAAAAbgBAQAAAAEBFQAAUAAgCIsBAQAAAAGTAUAAAAABlAFAAAAAAbQBAQAAAAG1AQEAAAABtgEBAAAAAbcBAgAAAAG4AQEAAAABARUAAFIAMAEVAABSADALBgAAqAIAIAkAAKcCACAKAADCAgAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhtAEBAJMCACG1AQEAkwIAIbYBAQCTAgAhtwECAKQCACG4AQEApQIAIQIAAAASACAVAABVACAIiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhtAEBAJMCACG1AQEAkwIAIbYBAQCTAgAhtwECAKQCACG4AQEApQIAIQIAAAAQACAVAABXACACAAAAEAAgFQAAVwAgAwAAABIAIBwAAFAAIB0AAFUAIAEAAAASACABAAAAEAAgBgQAALIDACAiAACzAwAgIwAAtgMAICQAALUDACAlAAC0AwAguAEAAJMDACALiAEAAPIBADCJAQAAXgAQigEAAPIBADCLAQEAwgEAIZMBQADFAQAhlAFAAMUBACG0AQEAwgEAIbUBAQDCAQAhtgEBAMIBACG3AQIA2QEAIbgBAQDYAQAhAwAAABAAIAEAAF0AMCEAAF4AIAMAAAAQACABAAARADACAAASACAJAwAA6gEAIIgBAADxAQAwiQEAAGQAEIoBAADxAQAwiwEBAAAAAYwBAQAAAAGTAUAA0wEAIZQBQADTAQAhsAEBAOYBACEBAAAAYQAgAQAAAGEAIAkDAADqAQAgiAEAAPEBADCJAQAAZAAQigEAAPEBADCLAQEA0AEAIYwBAQDQAQAhkwFAANMBACGUAUAA0wEAIbABAQDmAQAhAgMAAJsDACCwAQAAkwMAIAMAAABkACABAABlADACAABhACADAAAAZAAgAQAAZQAwAgAAYQAgAwAAAGQAIAEAAGUAMAIAAGEAIAYDAACxAwAgiwEBAAAAAYwBAQAAAAGTAUAAAAABlAFAAAAAAbABAQAAAAEBFQAAaQAgBYsBAQAAAAGMAQEAAAABkwFAAAAAAZQBQAAAAAGwAQEAAAABARUAAGsAMAEVAABrADAGAwAApwMAIIsBAQCTAgAhjAEBAJMCACGTAUAAlgIAIZQBQACWAgAhsAEBAKUCACECAAAAYQAgFQAAbgAgBYsBAQCTAgAhjAEBAJMCACGTAUAAlgIAIZQBQACWAgAhsAEBAKUCACECAAAAZAAgFQAAcAAgAgAAAGQAIBUAAHAAIAMAAABhACAcAABpACAdAABuACABAAAAYQAgAQAAAGQAIAQEAACkAwAgJAAApgMAICUAAKUDACCwAQAAkwMAIAiIAQAA8AEAMIkBAAB3ABCKAQAA8AEAMIsBAQDCAQAhjAEBAMIBACGTAUAAxQEAIZQBQADFAQAhsAEBANgBACEDAAAAZAAgAQAAdgAwIQAAdwAgAwAAAGQAIAEAAGUAMAIAAGEAIAEAAAAHACABAAAABwAgAwAAAAUAIAEAAAYAMAIAAAcAIAMAAAAFACABAAAGADACAAAHACADAAAABQAgAQAABgAwAgAABwAgDAUAAIcDACAGAACjAwAgBwAAiAMAIIsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAGwAQEAAAABsQEIAAAAAbIBAgAAAAGzAQEAAAABtAEBAAAAAQEVAAB_ACAJiwEBAAAAAZMBQAAAAAGUAUAAAAABrwEBAAAAAbABAQAAAAGxAQgAAAABsgECAAAAAbMBAQAAAAG0AQEAAAABARUAAIEBADABFQAAgQEAMAwFAAD7AgAgBgAAogMAIAcAAPwCACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbMBAQCTAgAhtAEBAJMCACECAAAABwAgFQAAhAEAIAmLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbMBAQCTAgAhtAEBAJMCACECAAAABQAgFQAAhgEAIAIAAAAFACAVAACGAQAgAwAAAAcAIBwAAH8AIB0AAIQBACABAAAABwAgAQAAAAUAIAcEAACdAwAgIgAAngMAICMAAKEDACAkAACgAwAgJQAAnwMAILABAACTAwAgsgEAAJMDACAMiAEAAOwBADCJAQAAjQEAEIoBAADsAQAwiwEBAMIBACGTAUAAxQEAIZQBQADFAQAhrwEBAMIBACGwAQEA2AEAIbEBCADbAQAhsgECAO0BACGzAQEAwgEAIbQBAQDCAQAhAwAAAAUAIAEAAIwBADAhAACNAQAgAwAAAAUAIAEAAAYAMAIAAAcAIBMDAADqAQAgBwAA1QEAIAgAAOsBACALAADWAQAgiAEAAOUBADCJAQAAAwAQigEAAOUBADCLAQEAAAABkwFAANMBACGUAUAA0wEAIaMBAQAAAAGkAQEA5gEAIaUBAgDnAQAhpgEAANoBACCnAQgA6AEAIagBIADpAQAhqQEIAOgBACGqAQIA5wEAIasBAQDmAQAhAQAAAJABACABAAAAkAEAIAYDAACbAwAgBwAAkQMAIAgAAJwDACALAACSAwAgpAEAAJMDACCrAQAAkwMAIAMAAAADACABAACTAQAwAgAAkAEAIAMAAAADACABAACTAQAwAgAAkAEAIAMAAAADACABAACTAQAwAgAAkAEAIBADAACKAwAgBwAAiwMAIAgAAJoDACALAACMAwAgiwEBAAAAAZMBQAAAAAGUAUAAAAABowEBAAAAAaQBAQAAAAGlAQIAAAABpgEAAIkDACCnAQgAAAABqAEgAAAAAakBCAAAAAGqAQIAAAABqwEBAAAAAQEVAACXAQAgDIsBAQAAAAGTAUAAAAABlAFAAAAAAaMBAQAAAAGkAQEAAAABpQECAAAAAaYBAACJAwAgpwEIAAAAAagBIAAAAAGpAQgAAAABqgECAAAAAasBAQAAAAEBFQAAmQEAMAEVAACZAQAwEAMAANgCACAHAADZAgAgCAAAmQMAIAsAANoCACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGjAQEAkwIAIaQBAQClAgAhpQECAKQCACGmAQAA1gIAIKcBCAC3AgAhqAEgANcCACGpAQgAtwIAIaoBAgCkAgAhqwEBAKUCACECAAAAkAEAIBUAAJwBACAMiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhowEBAJMCACGkAQEApQIAIaUBAgCkAgAhpgEAANYCACCnAQgAtwIAIagBIADXAgAhqQEIALcCACGqAQIApAIAIasBAQClAgAhAgAAAAMAIBUAAJ4BACACAAAAAwAgFQAAngEAIAMAAACQAQAgHAAAlwEAIB0AAJwBACABAAAAkAEAIAEAAAADACAHBAAAlAMAICIAAJUDACAjAACYAwAgJAAAlwMAICUAAJYDACCkAQAAkwMAIKsBAACTAwAgD4gBAADXAQAwiQEAAKUBABCKAQAA1wEAMIsBAQDCAQAhkwFAAMUBACGUAUAAxQEAIaMBAQDCAQAhpAEBANgBACGlAQIA2QEAIaYBAADaAQAgpwEIANsBACGoASAA3AEAIakBCADbAQAhqgECANkBACGrAQEA2AEAIQMAAAADACABAACkAQAwIQAApQEAIAMAAAADACABAACTAQAwAgAAkAEAIA4HAADVAQAgCwAA1gEAIAwAANQBACCIAQAAzwEAMIkBAACrAQAQigEAAM8BADCLAQEAAAABjAEBANABACGNAQEAAAABjgEBANABACGQAQAA0QGQASKSAQAA0gGSASKTAUAA0wEAIZQBQADTAQAhAQAAAKgBACABAAAAqAEAIA4HAADVAQAgCwAA1gEAIAwAANQBACCIAQAAzwEAMIkBAACrAQAQigEAAM8BADCLAQEA0AEAIYwBAQDQAQAhjQEBANABACGOAQEA0AEAIZABAADRAZABIpIBAADSAZIBIpMBQADTAQAhlAFAANMBACEDBwAAkQMAIAsAAJIDACAMAACQAwAgAwAAAKsBACABAACsAQAwAgAAqAEAIAMAAACrAQAgAQAArAEAMAIAAKgBACADAAAAqwEAIAEAAKwBADACAACoAQAgCwcAAI4DACALAACPAwAgDAAAjQMAIIsBAQAAAAGMAQEAAAABjQEBAAAAAY4BAQAAAAGQAQAAAJABApIBAAAAkgECkwFAAAAAAZQBQAAAAAEBFQAAsAEAIAiLAQEAAAABjAEBAAAAAY0BAQAAAAGOAQEAAAABkAEAAACQAQKSAQAAAJIBApMBQAAAAAGUAUAAAAABARUAALIBADABFQAAsgEAMAsHAACYAgAgCwAAmQIAIAwAAJcCACCLAQEAkwIAIYwBAQCTAgAhjQEBAJMCACGOAQEAkwIAIZABAACUApABIpIBAACVApIBIpMBQACWAgAhlAFAAJYCACECAAAAqAEAIBUAALUBACAIiwEBAJMCACGMAQEAkwIAIY0BAQCTAgAhjgEBAJMCACGQAQAAlAKQASKSAQAAlQKSASKTAUAAlgIAIZQBQACWAgAhAgAAAKsBACAVAAC3AQAgAgAAAKsBACAVAAC3AQAgAwAAAKgBACAcAACwAQAgHQAAtQEAIAEAAACoAQAgAQAAAKsBACADBAAAkAIAICQAAJICACAlAACRAgAgC4gBAADBAQAwiQEAAL4BABCKAQAAwQEAMIsBAQDCAQAhjAEBAMIBACGNAQEAwgEAIY4BAQDCAQAhkAEAAMMBkAEikgEAAMQBkgEikwFAAMUBACGUAUAAxQEAIQMAAACrAQAgAQAAvQEAMCEAAL4BACADAAAAqwEAIAEAAKwBADACAACoAQAgC4gBAADBAQAwiQEAAL4BABCKAQAAwQEAMIsBAQDCAQAhjAEBAMIBACGNAQEAwgEAIY4BAQDCAQAhkAEAAMMBkAEikgEAAMQBkgEikwFAAMUBACGUAUAAxQEAIQ4EAADHAQAgJAAAzgEAICUAAM4BACCVAQEAAAABlgEBAAAABJcBAQAAAASYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAM0BACGdAQEAAAABngEBAAAAAZ8BAQAAAAEHBAAAxwEAICQAAMwBACAlAADMAQAglQEAAACQAQKWAQAAAJABCJcBAAAAkAEInAEAAMsBkAEiBwQAAMcBACAkAADKAQAgJQAAygEAIJUBAAAAkgEClgEAAACSAQiXAQAAAJIBCJwBAADJAZIBIgsEAADHAQAgJAAAyAEAICUAAMgBACCVAUAAAAABlgFAAAAABJcBQAAAAASYAUAAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABnAFAAMYBACELBAAAxwEAICQAAMgBACAlAADIAQAglQFAAAAAAZYBQAAAAASXAUAAAAAEmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQADGAQAhCJUBAgAAAAGWAQIAAAAElwECAAAABJgBAgAAAAGZAQIAAAABmgECAAAAAZsBAgAAAAGcAQIAxwEAIQiVAUAAAAABlgFAAAAABJcBQAAAAASYAUAAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABnAFAAMgBACEHBAAAxwEAICQAAMoBACAlAADKAQAglQEAAACSAQKWAQAAAJIBCJcBAAAAkgEInAEAAMkBkgEiBJUBAAAAkgEClgEAAACSAQiXAQAAAJIBCJwBAADKAZIBIgcEAADHAQAgJAAAzAEAICUAAMwBACCVAQAAAJABApYBAAAAkAEIlwEAAACQAQicAQAAywGQASIElQEAAACQAQKWAQAAAJABCJcBAAAAkAEInAEAAMwBkAEiDgQAAMcBACAkAADOAQAgJQAAzgEAIJUBAQAAAAGWAQEAAAAElwEBAAAABJgBAQAAAAGZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAzQEAIZ0BAQAAAAGeAQEAAAABnwEBAAAAAQuVAQEAAAABlgEBAAAABJcBAQAAAASYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAM4BACGdAQEAAAABngEBAAAAAZ8BAQAAAAEOBwAA1QEAIAsAANYBACAMAADUAQAgiAEAAM8BADCJAQAAqwEAEIoBAADPAQAwiwEBANABACGMAQEA0AEAIY0BAQDQAQAhjgEBANABACGQAQAA0QGQASKSAQAA0gGSASKTAUAA0wEAIZQBQADTAQAhC5UBAQAAAAGWAQEAAAAElwEBAAAABJgBAQAAAAGZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAzgEAIZ0BAQAAAAGeAQEAAAABnwEBAAAAAQSVAQAAAJABApYBAAAAkAEIlwEAAACQAQicAQAAzAGQASIElQEAAACSAQKWAQAAAJIBCJcBAAAAkgEInAEAAMoBkgEiCJUBQAAAAAGWAUAAAAAElwFAAAAABJgBQAAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGcAUAAyAEAIRUDAADqAQAgBwAA1QEAIAgAAOsBACALAADWAQAgiAEAAOUBADCJAQAAAwAQigEAAOUBADCLAQEA0AEAIZMBQADTAQAhlAFAANMBACGjAQEA0AEAIaQBAQDmAQAhpQECAOcBACGmAQAA2gEAIKcBCADoAQAhqAEgAOkBACGpAQgA6AEAIaoBAgDnAQAhqwEBAOYBACHEAQAAAwAgxQEAAAMAIAOgAQAACwAgoQEAAAsAIKIBAAALACADoAEAABAAIKEBAAAQACCiAQAAEAAgD4gBAADXAQAwiQEAAKUBABCKAQAA1wEAMIsBAQDCAQAhkwFAAMUBACGUAUAAxQEAIaMBAQDCAQAhpAEBANgBACGlAQIA2QEAIaYBAADaAQAgpwEIANsBACGoASAA3AEAIakBCADbAQAhqgECANkBACGrAQEA2AEAIQ4EAADjAQAgJAAA5AEAICUAAOQBACCVAQEAAAABlgEBAAAABZcBAQAAAAWYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAOIBACGdAQEAAAABngEBAAAAAZ8BAQAAAAENBAAAxwEAICIAAOABACAjAADHAQAgJAAAxwEAICUAAMcBACCVAQIAAAABlgECAAAABJcBAgAAAASYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAOEBACEElQEBAAAABawBAQAAAAGtAQEAAAAErgEBAAAABA0EAADHAQAgIgAA4AEAICMAAOABACAkAADgAQAgJQAA4AEAIJUBCAAAAAGWAQgAAAAElwEIAAAABJgBCAAAAAGZAQgAAAABmgEIAAAAAZsBCAAAAAGcAQgA3wEAIQUEAADHAQAgJAAA3gEAICUAAN4BACCVASAAAAABnAEgAN0BACEFBAAAxwEAICQAAN4BACAlAADeAQAglQEgAAAAAZwBIADdAQAhApUBIAAAAAGcASAA3gEAIQ0EAADHAQAgIgAA4AEAICMAAOABACAkAADgAQAgJQAA4AEAIJUBCAAAAAGWAQgAAAAElwEIAAAABJgBCAAAAAGZAQgAAAABmgEIAAAAAZsBCAAAAAGcAQgA3wEAIQiVAQgAAAABlgEIAAAABJcBCAAAAASYAQgAAAABmQEIAAAAAZoBCAAAAAGbAQgAAAABnAEIAOABACENBAAAxwEAICIAAOABACAjAADHAQAgJAAAxwEAICUAAMcBACCVAQIAAAABlgECAAAABJcBAgAAAASYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAOEBACEOBAAA4wEAICQAAOQBACAlAADkAQAglQEBAAAAAZYBAQAAAAWXAQEAAAAFmAEBAAAAAZkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQDiAQAhnQEBAAAAAZ4BAQAAAAGfAQEAAAABCJUBAgAAAAGWAQIAAAAFlwECAAAABZgBAgAAAAGZAQIAAAABmgECAAAAAZsBAgAAAAGcAQIA4wEAIQuVAQEAAAABlgEBAAAABZcBAQAAAAWYAQEAAAABmQEBAAAAAZoBAQAAAAGbAQEAAAABnAEBAOQBACGdAQEAAAABngEBAAAAAZ8BAQAAAAETAwAA6gEAIAcAANUBACAIAADrAQAgCwAA1gEAIIgBAADlAQAwiQEAAAMAEIoBAADlAQAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhowEBANABACGkAQEA5gEAIaUBAgDnAQAhpgEAANoBACCnAQgA6AEAIagBIADpAQAhqQEIAOgBACGqAQIA5wEAIasBAQDmAQAhC5UBAQAAAAGWAQEAAAAFlwEBAAAABZgBAQAAAAGZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEA5AEAIZ0BAQAAAAGeAQEAAAABnwEBAAAAAQiVAQIAAAABlgECAAAABJcBAgAAAASYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAMcBACEIlQEIAAAAAZYBCAAAAASXAQgAAAAEmAEIAAAAAZkBCAAAAAGaAQgAAAABmwEIAAAAAZwBCADgAQAhApUBIAAAAAGcASAA3gEAIQOgAQAABQAgoQEAAAUAIKIBAAAFACAQBwAA1QEAIAsAANYBACAMAADUAQAgiAEAAM8BADCJAQAAqwEAEIoBAADPAQAwiwEBANABACGMAQEA0AEAIY0BAQDQAQAhjgEBANABACGQAQAA0QGQASKSAQAA0gGSASKTAUAA0wEAIZQBQADTAQAhxAEAAKsBACDFAQAAqwEAIAyIAQAA7AEAMIkBAACNAQAQigEAAOwBADCLAQEAwgEAIZMBQADFAQAhlAFAAMUBACGvAQEAwgEAIbABAQDYAQAhsQEIANsBACGyAQIA7QEAIbMBAQDCAQAhtAEBAMIBACENBAAA4wEAICIAAO8BACAjAADjAQAgJAAA4wEAICUAAOMBACCVAQIAAAABlgECAAAABZcBAgAAAAWYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAO4BACENBAAA4wEAICIAAO8BACAjAADjAQAgJAAA4wEAICUAAOMBACCVAQIAAAABlgECAAAABZcBAgAAAAWYAQIAAAABmQECAAAAAZoBAgAAAAGbAQIAAAABnAECAO4BACEIlQEIAAAAAZYBCAAAAAWXAQgAAAAFmAEIAAAAAZkBCAAAAAGaAQgAAAABmwEIAAAAAZwBCADvAQAhCIgBAADwAQAwiQEAAHcAEIoBAADwAQAwiwEBAMIBACGMAQEAwgEAIZMBQADFAQAhlAFAAMUBACGwAQEA2AEAIQkDAADqAQAgiAEAAPEBADCJAQAAZAAQigEAAPEBADCLAQEA0AEAIYwBAQDQAQAhkwFAANMBACGUAUAA0wEAIbABAQDmAQAhC4gBAADyAQAwiQEAAF4AEIoBAADyAQAwiwEBAMIBACGTAUAAxQEAIZQBQADFAQAhtAEBAMIBACG1AQEAwgEAIbYBAQDCAQAhtwECANkBACG4AQEA2AEAIQyIAQAA8wEAMIkBAABIABCKAQAA8wEAMIsBAQDCAQAhkgEAAPUBvgEikwFAAMUBACGUAUAAxQEAIbUBAQDCAQAhuQEBAMIBACG6AQgA2wEAIbwBAAD0AbwBIr4BQAD2AQAhBwQAAMcBACAkAAD8AQAgJQAA_AEAIJUBAAAAvAEClgEAAAC8AQiXAQAAALwBCJwBAAD7AbwBIgcEAADHAQAgJAAA-gEAICUAAPoBACCVAQAAAL4BApYBAAAAvgEIlwEAAAC-AQicAQAA-QG-ASILBAAA4wEAICQAAPgBACAlAAD4AQAglQFAAAAAAZYBQAAAAAWXAUAAAAAFmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQAD3AQAhCwQAAOMBACAkAAD4AQAgJQAA-AEAIJUBQAAAAAGWAUAAAAAFlwFAAAAABZgBQAAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGcAUAA9wEAIQiVAUAAAAABlgFAAAAABZcBQAAAAAWYAUAAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABnAFAAPgBACEHBAAAxwEAICQAAPoBACAlAAD6AQAglQEAAAC-AQKWAQAAAL4BCJcBAAAAvgEInAEAAPkBvgEiBJUBAAAAvgEClgEAAAC-AQiXAQAAAL4BCJwBAAD6Ab4BIgcEAADHAQAgJAAA_AEAICUAAPwBACCVAQAAALwBApYBAAAAvAEIlwEAAAC8AQicAQAA-wG8ASIElQEAAAC8AQKWAQAAALwBCJcBAAAAvAEInAEAAPwBvAEiDQkAAIECACCIAQAA_QEAMIkBAAAbABCKAQAA_QEAMIsBAQDQAQAhkgEAAP8BvgEikwFAANMBACGUAUAA0wEAIbUBAQDQAQAhuQEBANABACG6AQgA6AEAIbwBAAD-AbwBIr4BQACAAgAhBJUBAAAAvAEClgEAAAC8AQiXAQAAALwBCJwBAAD8AbwBIgSVAQAAAL4BApYBAAAAvgEIlwEAAAC-AQicAQAA-gG-ASIIlQFAAAAAAZYBQAAAAAWXAUAAAAAFmAFAAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAZwBQAD4AQAhFQYAAIcCACAKAADrAQAgDQAAigIAIA4AAIsCACAPAACMAgAgiAEAAIgCADCJAQAACwAQigEAAIgCADCLAQEA0AEAIZIBAACJAsEBIpMBQADTAQAhlAFAANMBACGxAQgA6AEAIbQBAQDQAQAhtgEBANABACG_AQEA0AEAIcEBQADTAQAhwgEBANABACHDAQEA5gEAIcQBAAALACDFAQAACwAgDogBAACCAgAwiQEAADAAEIoBAACCAgAwiwEBAMIBACGSAQAAgwLBASKTAUAAxQEAIZQBQADFAQAhsQEIANsBACG0AQEAwgEAIbYBAQDCAQAhvwEBAMIBACHBAUAAxQEAIcIBAQDCAQAhwwEBANgBACEHBAAAxwEAICQAAIUCACAlAACFAgAglQEAAADBAQKWAQAAAMEBCJcBAAAAwQEInAEAAIQCwQEiBwQAAMcBACAkAACFAgAgJQAAhQIAIJUBAAAAwQEClgEAAADBAQiXAQAAAMEBCJwBAACEAsEBIgSVAQAAAMEBApYBAAAAwQEIlwEAAADBAQicAQAAhQLBASIOBgAAhwIAIAkAAIECACAKAADrAQAgiAEAAIYCADCJAQAAEAAQigEAAIYCADCLAQEA0AEAIZMBQADTAQAhlAFAANMBACG0AQEA0AEAIbUBAQDQAQAhtgEBANABACG3AQIA5wEAIbgBAQDmAQAhFQMAAOoBACAHAADVAQAgCAAA6wEAIAsAANYBACCIAQAA5QEAMIkBAAADABCKAQAA5QEAMIsBAQDQAQAhkwFAANMBACGUAUAA0wEAIaMBAQDQAQAhpAEBAOYBACGlAQIA5wEAIaYBAADaAQAgpwEIAOgBACGoASAA6QEAIakBCADoAQAhqgECAOcBACGrAQEA5gEAIcQBAAADACDFAQAAAwAgEwYAAIcCACAKAADrAQAgDQAAigIAIA4AAIsCACAPAACMAgAgiAEAAIgCADCJAQAACwAQigEAAIgCADCLAQEA0AEAIZIBAACJAsEBIpMBQADTAQAhlAFAANMBACGxAQgA6AEAIbQBAQDQAQAhtgEBANABACG_AQEA0AEAIcEBQADTAQAhwgEBANABACHDAQEA5gEAIQSVAQAAAMEBApYBAAAAwQEIlwEAAADBAQicAQAAhQLBASIRBQAAjwIAIAYAAIcCACAHAADVAQAgiAEAAI0CADCJAQAABQAQigEAAI0CADCLAQEA0AEAIZMBQADTAQAhlAFAANMBACGvAQEA0AEAIbABAQDmAQAhsQEIAOgBACGyAQIAjgIAIbMBAQDQAQAhtAEBANABACHEAQAABQAgxQEAAAUAIA8JAACBAgAgiAEAAP0BADCJAQAAGwAQigEAAP0BADCLAQEA0AEAIZIBAAD_Ab4BIpMBQADTAQAhlAFAANMBACG1AQEA0AEAIbkBAQDQAQAhugEIAOgBACG8AQAA_gG8ASK-AUAAgAIAIcQBAAAbACDFAQAAGwAgEAYAAIcCACAJAACBAgAgCgAA6wEAIIgBAACGAgAwiQEAABAAEIoBAACGAgAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhtAEBANABACG1AQEA0AEAIbYBAQDQAQAhtwECAOcBACG4AQEA5gEAIcQBAAAQACDFAQAAEAAgDwUAAI8CACAGAACHAgAgBwAA1QEAIIgBAACNAgAwiQEAAAUAEIoBAACNAgAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhrwEBANABACGwAQEA5gEAIbEBCADoAQAhsgECAI4CACGzAQEA0AEAIbQBAQDQAQAhCJUBAgAAAAGWAQIAAAAFlwECAAAABZgBAgAAAAGZAQIAAAABmgECAAAAAZsBAgAAAAGcAQIA4wEAIQsDAADqAQAgiAEAAPEBADCJAQAAZAAQigEAAPEBADCLAQEA0AEAIYwBAQDQAQAhkwFAANMBACGUAUAA0wEAIbABAQDmAQAhxAEAAGQAIMUBAABkACAAAAAByQEBAAAAAQHJAQAAAJABAgHJAQAAAJIBAgHJAUAAAAABBxwAANECACAdAADUAgAgxgEAANICACDHAQAA0wIAIMoBAAADACDLAQAAAwAgzAEAAJABACALHAAArAIAMB0AALECADDGAQAArQIAMMcBAACuAgAwyAEAAK8CACDJAQAAsAIAMMoBAACwAgAwywEAALACADDMAQAAsAIAMM0BAACyAgAwzgEAALMCADALHAAAmgIAMB0AAJ8CADDGAQAAmwIAMMcBAACcAgAwyAEAAJ0CACDJAQAAngIAMMoBAACeAgAwywEAAJ4CADDMAQAAngIAMM0BAACgAgAwzgEAAKECADAJBgAAqwIAIAkAAKoCACCLAQEAAAABkwFAAAAAAZQBQAAAAAG0AQEAAAABtQEBAAAAAbcBAgAAAAG4AQEAAAABAgAAABIAIBwAAKkCACADAAAAEgAgHAAAqQIAIB0AAKYCACABFQAAgAQAMA4GAACHAgAgCQAAgQIAIAoAAOsBACCIAQAAhgIAMIkBAAAQABCKAQAAhgIAMIsBAQAAAAGTAUAA0wEAIZQBQADTAQAhtAEBANABACG1AQEAAAABtgEBANABACG3AQIA5wEAIbgBAQDmAQAhAgAAABIAIBUAAKYCACACAAAAogIAIBUAAKMCACALiAEAAKECADCJAQAAogIAEIoBAAChAgAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhtAEBANABACG1AQEA0AEAIbYBAQDQAQAhtwECAOcBACG4AQEA5gEAIQuIAQAAoQIAMIkBAACiAgAQigEAAKECADCLAQEA0AEAIZMBQADTAQAhlAFAANMBACG0AQEA0AEAIbUBAQDQAQAhtgEBANABACG3AQIA5wEAIbgBAQDmAQAhB4sBAQCTAgAhkwFAAJYCACGUAUAAlgIAIbQBAQCTAgAhtQEBAJMCACG3AQIApAIAIbgBAQClAgAhBckBAgAAAAHPAQIAAAAB0AECAAAAAdEBAgAAAAHSAQIAAAABAckBAQAAAAEJBgAAqAIAIAkAAKcCACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACG0AQEAkwIAIbUBAQCTAgAhtwECAKQCACG4AQEApQIAIQUcAAD4AwAgHQAA_gMAIMYBAAD5AwAgxwEAAP0DACDMAQAAAQAgBRwAAPYDACAdAAD7AwAgxgEAAPcDACDHAQAA-gMAIMwBAACQAQAgCQYAAKsCACAJAACqAgAgiwEBAAAAAZMBQAAAAAGUAUAAAAABtAEBAAAAAbUBAQAAAAG3AQIAAAABuAEBAAAAAQMcAAD4AwAgxgEAAPkDACDMAQAAAQAgAxwAAPYDACDGAQAA9wMAIMwBAACQAQAgDgYAAM4CACANAADNAgAgDgAAzwIAIA8AANACACCLAQEAAAABkgEAAADBAQKTAUAAAAABlAFAAAAAAbEBCAAAAAG0AQEAAAABvwEBAAAAAcEBQAAAAAHCAQEAAAABwwEBAAAAAQIAAAABACAcAADMAgAgAwAAAAEAIBwAAMwCACAdAAC4AgAgARUAAPUDADATBgAAhwIAIAoAAOsBACANAACKAgAgDgAAiwIAIA8AAIwCACCIAQAAiAIAMIkBAAALABCKAQAAiAIAMIsBAQAAAAGSAQAAiQLBASKTAUAA0wEAIZQBQADTAQAhsQEIAOgBACG0AQEA0AEAIbYBAQDQAQAhvwEBANABACHBAUAA0wEAIcIBAQDQAQAhwwEBAOYBACECAAAAAQAgFQAAuAIAIAIAAAC0AgAgFQAAtQIAIA6IAQAAswIAMIkBAAC0AgAQigEAALMCADCLAQEA0AEAIZIBAACJAsEBIpMBQADTAQAhlAFAANMBACGxAQgA6AEAIbQBAQDQAQAhtgEBANABACG_AQEA0AEAIcEBQADTAQAhwgEBANABACHDAQEA5gEAIQ6IAQAAswIAMIkBAAC0AgAQigEAALMCADCLAQEA0AEAIZIBAACJAsEBIpMBQADTAQAhlAFAANMBACGxAQgA6AEAIbQBAQDQAQAhtgEBANABACG_AQEA0AEAIcEBQADTAQAhwgEBANABACHDAQEA5gEAIQqLAQEAkwIAIZIBAAC2AsEBIpMBQACWAgAhlAFAAJYCACGxAQgAtwIAIbQBAQCTAgAhvwEBAJMCACHBAUAAlgIAIcIBAQCTAgAhwwEBAKUCACEByQEAAADBAQIFyQEIAAAAAc8BCAAAAAHQAQgAAAAB0QEIAAAAAdIBCAAAAAEOBgAAugIAIA0AALkCACAOAAC7AgAgDwAAvAIAIIsBAQCTAgAhkgEAALYCwQEikwFAAJYCACGUAUAAlgIAIbEBCAC3AgAhtAEBAJMCACG_AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQUcAADoAwAgHQAA8wMAIMYBAADpAwAgxwEAAPIDACDMAQAABwAgBRwAAOYDACAdAADwAwAgxgEAAOcDACDHAQAA7wMAIMwBAACQAQAgBxwAAMQCACAdAADHAgAgxgEAAMUCACDHAQAAxgIAIMoBAAAbACDLAQAAGwAgzAEAADMAIAccAAC9AgAgHQAAwAIAIMYBAAC-AgAgxwEAAL8CACDKAQAAEAAgywEAABAAIMwBAAASACAJBgAAqwIAIAoAAMMCACCLAQEAAAABkwFAAAAAAZQBQAAAAAG0AQEAAAABtgEBAAAAAbcBAgAAAAG4AQEAAAABAgAAABIAIBwAAL0CACADAAAAEAAgHAAAvQIAIB0AAMECACALAAAAEAAgBgAAqAIAIAoAAMICACAVAADBAgAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhtAEBAJMCACG2AQEAkwIAIbcBAgCkAgAhuAEBAKUCACEJBgAAqAIAIAoAAMICACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACG0AQEAkwIAIbYBAQCTAgAhtwECAKQCACG4AQEApQIAIQUcAADqAwAgHQAA7QMAIMYBAADrAwAgxwEAAOwDACDMAQAAqAEAIAMcAADqAwAgxgEAAOsDACDMAQAAqAEAIAiLAQEAAAABkgEAAAC-AQKTAUAAAAABlAFAAAAAAbkBAQAAAAG6AQgAAAABvAEAAAC8AQK-AUAAAAABAgAAADMAIBwAAMQCACADAAAAGwAgHAAAxAIAIB0AAMgCACAKAAAAGwAgFQAAyAIAIIsBAQCTAgAhkgEAAMoCvgEikwFAAJYCACGUAUAAlgIAIbkBAQCTAgAhugEIALcCACG8AQAAyQK8ASK-AUAAywIAIQiLAQEAkwIAIZIBAADKAr4BIpMBQACWAgAhlAFAAJYCACG5AQEAkwIAIboBCAC3AgAhvAEAAMkCvAEivgFAAMsCACEByQEAAAC8AQIByQEAAAC-AQIByQFAAAAAAQ4GAADOAgAgDQAAzQIAIA4AAM8CACAPAADQAgAgiwEBAAAAAZIBAAAAwQECkwFAAAAAAZQBQAAAAAGxAQgAAAABtAEBAAAAAb8BAQAAAAHBAUAAAAABwgEBAAAAAcMBAQAAAAEDHAAA6AMAIMYBAADpAwAgzAEAAAcAIAMcAADmAwAgxgEAAOcDACDMAQAAkAEAIAMcAADEAgAgxgEAAMUCACDMAQAAMwAgAxwAAL0CACDGAQAAvgIAIMwBAAASACAOAwAAigMAIAcAAIsDACALAACMAwAgiwEBAAAAAZMBQAAAAAGUAUAAAAABpAEBAAAAAaUBAgAAAAGmAQAAiQMAIKcBCAAAAAGoASAAAAABqQEIAAAAAaoBAgAAAAGrAQEAAAABAgAAAJABACAcAADRAgAgAwAAAAMAIBwAANECACAdAADVAgAgEAAAAAMAIAMAANgCACAHAADZAgAgCwAA2gIAIBUAANUCACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGkAQEApQIAIaUBAgCkAgAhpgEAANYCACCnAQgAtwIAIagBIADXAgAhqQEIALcCACGqAQIApAIAIasBAQClAgAhDgMAANgCACAHAADZAgAgCwAA2gIAIIsBAQCTAgAhkwFAAJYCACGUAUAAlgIAIaQBAQClAgAhpQECAKQCACGmAQAA1gIAIKcBCAC3AgAhqAEgANcCACGpAQgAtwIAIaoBAgCkAgAhqwEBAKUCACECyQEBAAAABNMBAQAAAAUByQEgAAAAAQscAADvAgAwHQAA9AIAMMYBAADwAgAwxwEAAPECADDIAQAA8gIAIMkBAADzAgAwygEAAPMCADDLAQAA8wIAMMwBAADzAgAwzQEAAPUCADDOAQAA9gIAMAscAADkAgAwHQAA6AIAMMYBAADlAgAwxwEAAOYCADDIAQAA5wIAIMkBAACwAgAwygEAALACADDLAQAAsAIAMMwBAACwAgAwzQEAAOkCADDOAQAAswIAMAscAADbAgAwHQAA3wIAMMYBAADcAgAwxwEAAN0CADDIAQAA3gIAIMkBAACeAgAwygEAAJ4CADDLAQAAngIAMMwBAACeAgAwzQEAAOACADDOAQAAoQIAMAkJAACqAgAgCgAAwwIAIIsBAQAAAAGTAUAAAAABlAFAAAAAAbUBAQAAAAG2AQEAAAABtwECAAAAAbgBAQAAAAECAAAAEgAgHAAA4wIAIAMAAAASACAcAADjAgAgHQAA4gIAIAEVAADlAwAwAgAAABIAIBUAAOICACACAAAAogIAIBUAAOECACAHiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhtQEBAJMCACG2AQEAkwIAIbcBAgCkAgAhuAEBAKUCACEJCQAApwIAIAoAAMICACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACG1AQEAkwIAIbYBAQCTAgAhtwECAKQCACG4AQEApQIAIQkJAACqAgAgCgAAwwIAIIsBAQAAAAGTAUAAAAABlAFAAAAAAbUBAQAAAAG2AQEAAAABtwECAAAAAbgBAQAAAAEOCgAA7gIAIA0AAM0CACAOAADPAgAgDwAA0AIAIIsBAQAAAAGSAQAAAMEBApMBQAAAAAGUAUAAAAABsQEIAAAAAbYBAQAAAAG_AQEAAAABwQFAAAAAAcIBAQAAAAHDAQEAAAABAgAAAAEAIBwAAO0CACADAAAAAQAgHAAA7QIAIB0AAOsCACABFQAA5AMAMAIAAAABACAVAADrAgAgAgAAALQCACAVAADqAgAgCosBAQCTAgAhkgEAALYCwQEikwFAAJYCACGUAUAAlgIAIbEBCAC3AgAhtgEBAJMCACG_AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQ4KAADsAgAgDQAAuQIAIA4AALsCACAPAAC8AgAgiwEBAJMCACGSAQAAtgLBASKTAUAAlgIAIZQBQACWAgAhsQEIALcCACG2AQEAkwIAIb8BAQCTAgAhwQFAAJYCACHCAQEAkwIAIcMBAQClAgAhBRwAAN8DACAdAADiAwAgxgEAAOADACDHAQAA4QMAIMwBAACoAQAgDgoAAO4CACANAADNAgAgDgAAzwIAIA8AANACACCLAQEAAAABkgEAAADBAQKTAUAAAAABlAFAAAAAAbEBCAAAAAG2AQEAAAABvwEBAAAAAcEBQAAAAAHCAQEAAAABwwEBAAAAAQMcAADfAwAgxgEAAOADACDMAQAAqAEAIAoFAACHAwAgBwAAiAMAIIsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAGwAQEAAAABsQEIAAAAAbIBAgAAAAGzAQEAAAABAgAAAAcAIBwAAIYDACADAAAABwAgHAAAhgMAIB0AAPoCACABFQAA3gMAMA8FAACPAgAgBgAAhwIAIAcAANUBACCIAQAAjQIAMIkBAAAFABCKAQAAjQIAMIsBAQAAAAGTAUAA0wEAIZQBQADTAQAhrwEBANABACGwAQEA5gEAIbEBCADoAQAhsgECAI4CACGzAQEA0AEAIbQBAQDQAQAhAgAAAAcAIBUAAPoCACACAAAA9wIAIBUAAPgCACAMiAEAAPYCADCJAQAA9wIAEIoBAAD2AgAwiwEBANABACGTAUAA0wEAIZQBQADTAQAhrwEBANABACGwAQEA5gEAIbEBCADoAQAhsgECAI4CACGzAQEA0AEAIbQBAQDQAQAhDIgBAAD2AgAwiQEAAPcCABCKAQAA9gIAMIsBAQDQAQAhkwFAANMBACGUAUAA0wEAIa8BAQDQAQAhsAEBAOYBACGxAQgA6AEAIbIBAgCOAgAhswEBANABACG0AQEA0AEAIQiLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbMBAQCTAgAhBckBAgAAAAHPAQIAAAAB0AECAAAAAdEBAgAAAAHSAQIAAAABCgUAAPsCACAHAAD8AgAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhrwEBAJMCACGwAQEApQIAIbEBCAC3AgAhsgECAPkCACGzAQEAkwIAIQUcAADYAwAgHQAA3AMAIMYBAADZAwAgxwEAANsDACDMAQAAYQAgCxwAAP0CADAdAACBAwAwxgEAAP4CADDHAQAA_wIAMMgBAACAAwAgyQEAALACADDKAQAAsAIAMMsBAACwAgAwzAEAALACADDNAQAAggMAMM4BAACzAgAwDgYAAM4CACAKAADuAgAgDgAAzwIAIA8AANACACCLAQEAAAABkgEAAADBAQKTAUAAAAABlAFAAAAAAbEBCAAAAAG0AQEAAAABtgEBAAAAAcEBQAAAAAHCAQEAAAABwwEBAAAAAQIAAAABACAcAACFAwAgAwAAAAEAIBwAAIUDACAdAACEAwAgARUAANoDADACAAAAAQAgFQAAhAMAIAIAAAC0AgAgFQAAgwMAIAqLAQEAkwIAIZIBAAC2AsEBIpMBQACWAgAhlAFAAJYCACGxAQgAtwIAIbQBAQCTAgAhtgEBAJMCACHBAUAAlgIAIcIBAQCTAgAhwwEBAKUCACEOBgAAugIAIAoAAOwCACAOAAC7AgAgDwAAvAIAIIsBAQCTAgAhkgEAALYCwQEikwFAAJYCACGUAUAAlgIAIbEBCAC3AgAhtAEBAJMCACG2AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQ4GAADOAgAgCgAA7gIAIA4AAM8CACAPAADQAgAgiwEBAAAAAZIBAAAAwQECkwFAAAAAAZQBQAAAAAGxAQgAAAABtAEBAAAAAbYBAQAAAAHBAUAAAAABwgEBAAAAAcMBAQAAAAEKBQAAhwMAIAcAAIgDACCLAQEAAAABkwFAAAAAAZQBQAAAAAGvAQEAAAABsAEBAAAAAbEBCAAAAAGyAQIAAAABswEBAAAAAQMcAADYAwAgxgEAANkDACDMAQAAYQAgBBwAAP0CADDGAQAA_gIAMMgBAACAAwAgzAEAALACADAByQEBAAAABAQcAADvAgAwxgEAAPACADDIAQAA8gIAIMwBAADzAgAwBBwAAOQCADDGAQAA5QIAMMgBAADnAgAgzAEAALACADAEHAAA2wIAMMYBAADcAgAwyAEAAN4CACDMAQAAngIAMAMcAADRAgAgxgEAANICACDMAQAAkAEAIAQcAACsAgAwxgEAAK0CADDIAQAArwIAIMwBAACwAgAwBBwAAJoCADDGAQAAmwIAMMgBAACdAgAgzAEAAJ4CADAGAwAAmwMAIAcAAJEDACAIAACcAwAgCwAAkgMAIKQBAACTAwAgqwEAAJMDACAAAAAAAAAAAAUcAADTAwAgHQAA1gMAIMYBAADUAwAgxwEAANUDACDMAQAAqAEAIAMcAADTAwAgxgEAANQDACDMAQAAqAEAIAADBwAAkQMAIAsAAJIDACAMAACQAwAgAAAAAAAFHAAAzgMAIB0AANEDACDGAQAAzwMAIMcBAADQAwAgzAEAAJABACADHAAAzgMAIMYBAADPAwAgzAEAAJABACAAAAALHAAAqAMAMB0AAKwDADDGAQAAqQMAMMcBAACqAwAwyAEAAKsDACDJAQAA8wIAMMoBAADzAgAwywEAAPMCADDMAQAA8wIAMM0BAACtAwAwzgEAAPYCADAKBgAAowMAIAcAAIgDACCLAQEAAAABkwFAAAAAAZQBQAAAAAGvAQEAAAABsAEBAAAAAbEBCAAAAAGyAQIAAAABtAEBAAAAAQIAAAAHACAcAACwAwAgAwAAAAcAIBwAALADACAdAACvAwAgARUAAM0DADACAAAABwAgFQAArwMAIAIAAAD3AgAgFQAArgMAIAiLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbQBAQCTAgAhCgYAAKIDACAHAAD8AgAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhrwEBAJMCACGwAQEApQIAIbEBCAC3AgAhsgECAPkCACG0AQEAkwIAIQoGAACjAwAgBwAAiAMAIIsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAGwAQEAAAABsQEIAAAAAbIBAgAAAAG0AQEAAAABBBwAAKgDADDGAQAAqQMAMMgBAACrAwAgzAEAAPMCADAAAAAAAAAAAAAABRwAAMgDACAdAADLAwAgxgEAAMkDACDHAQAAygMAIMwBAAABACADHAAAyAMAIMYBAADJAwAgzAEAAAEAIAYGAACQAwAgCgAAnAMAIA0AAMQDACAOAADFAwAgDwAAxgMAIMMBAACTAwAgAAAAAAAFBQAAxwMAIAYAAJADACAHAACRAwAgsAEAAJMDACCyAQAAkwMAIAIJAAC-AwAgvgEAAJMDACAEBgAAkAMAIAkAAL4DACAKAACcAwAguAEAAJMDACACAwAAmwMAILABAACTAwAgDwYAAM4CACAKAADuAgAgDQAAzQIAIA8AANACACCLAQEAAAABkgEAAADBAQKTAUAAAAABlAFAAAAAAbEBCAAAAAG0AQEAAAABtgEBAAAAAb8BAQAAAAHBAUAAAAABwgEBAAAAAcMBAQAAAAECAAAAAQAgHAAAyAMAIAMAAAALACAcAADIAwAgHQAAzAMAIBEAAAALACAGAAC6AgAgCgAA7AIAIA0AALkCACAPAAC8AgAgFQAAzAMAIIsBAQCTAgAhkgEAALYCwQEikwFAAJYCACGUAUAAlgIAIbEBCAC3AgAhtAEBAJMCACG2AQEAkwIAIb8BAQCTAgAhwQFAAJYCACHCAQEAkwIAIcMBAQClAgAhDwYAALoCACAKAADsAgAgDQAAuQIAIA8AALwCACCLAQEAkwIAIZIBAAC2AsEBIpMBQACWAgAhlAFAAJYCACGxAQgAtwIAIbQBAQCTAgAhtgEBAJMCACG_AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQiLAQEAAAABkwFAAAAAAZQBQAAAAAGvAQEAAAABsAEBAAAAAbEBCAAAAAGyAQIAAAABtAEBAAAAAQ8HAACLAwAgCAAAmgMAIAsAAIwDACCLAQEAAAABkwFAAAAAAZQBQAAAAAGjAQEAAAABpAEBAAAAAaUBAgAAAAGmAQAAiQMAIKcBCAAAAAGoASAAAAABqQEIAAAAAaoBAgAAAAGrAQEAAAABAgAAAJABACAcAADOAwAgAwAAAAMAIBwAAM4DACAdAADSAwAgEQAAAAMAIAcAANkCACAIAACZAwAgCwAA2gIAIBUAANIDACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGjAQEAkwIAIaQBAQClAgAhpQECAKQCACGmAQAA1gIAIKcBCAC3AgAhqAEgANcCACGpAQgAtwIAIaoBAgCkAgAhqwEBAKUCACEPBwAA2QIAIAgAAJkDACALAADaAgAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhowEBAJMCACGkAQEApQIAIaUBAgCkAgAhpgEAANYCACCnAQgAtwIAIagBIADXAgAhqQEIALcCACGqAQIApAIAIasBAQClAgAhCgcAAI4DACALAACPAwAgiwEBAAAAAYwBAQAAAAGNAQEAAAABjgEBAAAAAZABAAAAkAECkgEAAACSAQKTAUAAAAABlAFAAAAAAQIAAACoAQAgHAAA0wMAIAMAAACrAQAgHAAA0wMAIB0AANcDACAMAAAAqwEAIAcAAJgCACALAACZAgAgFQAA1wMAIIsBAQCTAgAhjAEBAJMCACGNAQEAkwIAIY4BAQCTAgAhkAEAAJQCkAEikgEAAJUCkgEikwFAAJYCACGUAUAAlgIAIQoHAACYAgAgCwAAmQIAIIsBAQCTAgAhjAEBAJMCACGNAQEAkwIAIY4BAQCTAgAhkAEAAJQCkAEikgEAAJUCkgEikwFAAJYCACGUAUAAlgIAIQWLAQEAAAABjAEBAAAAAZMBQAAAAAGUAUAAAAABsAEBAAAAAQIAAABhACAcAADYAwAgCosBAQAAAAGSAQAAAMEBApMBQAAAAAGUAUAAAAABsQEIAAAAAbQBAQAAAAG2AQEAAAABwQFAAAAAAcIBAQAAAAHDAQEAAAABAwAAAGQAIBwAANgDACAdAADdAwAgBwAAAGQAIBUAAN0DACCLAQEAkwIAIYwBAQCTAgAhkwFAAJYCACGUAUAAlgIAIbABAQClAgAhBYsBAQCTAgAhjAEBAJMCACGTAUAAlgIAIZQBQACWAgAhsAEBAKUCACEIiwEBAAAAAZMBQAAAAAGUAUAAAAABrwEBAAAAAbABAQAAAAGxAQgAAAABsgECAAAAAbMBAQAAAAEKCwAAjwMAIAwAAI0DACCLAQEAAAABjAEBAAAAAY0BAQAAAAGOAQEAAAABkAEAAACQAQKSAQAAAJIBApMBQAAAAAGUAUAAAAABAgAAAKgBACAcAADfAwAgAwAAAKsBACAcAADfAwAgHQAA4wMAIAwAAACrAQAgCwAAmQIAIAwAAJcCACAVAADjAwAgiwEBAJMCACGMAQEAkwIAIY0BAQCTAgAhjgEBAJMCACGQAQAAlAKQASKSAQAAlQKSASKTAUAAlgIAIZQBQACWAgAhCgsAAJkCACAMAACXAgAgiwEBAJMCACGMAQEAkwIAIY0BAQCTAgAhjgEBAJMCACGQAQAAlAKQASKSAQAAlQKSASKTAUAAlgIAIZQBQACWAgAhCosBAQAAAAGSAQAAAMEBApMBQAAAAAGUAUAAAAABsQEIAAAAAbYBAQAAAAG_AQEAAAABwQFAAAAAAcIBAQAAAAHDAQEAAAABB4sBAQAAAAGTAUAAAAABlAFAAAAAAbUBAQAAAAG2AQEAAAABtwECAAAAAbgBAQAAAAEPAwAAigMAIAgAAJoDACALAACMAwAgiwEBAAAAAZMBQAAAAAGUAUAAAAABowEBAAAAAaQBAQAAAAGlAQIAAAABpgEAAIkDACCnAQgAAAABqAEgAAAAAakBCAAAAAGqAQIAAAABqwEBAAAAAQIAAACQAQAgHAAA5gMAIAsFAACHAwAgBgAAowMAIIsBAQAAAAGTAUAAAAABlAFAAAAAAa8BAQAAAAGwAQEAAAABsQEIAAAAAbIBAgAAAAGzAQEAAAABtAEBAAAAAQIAAAAHACAcAADoAwAgCgcAAI4DACAMAACNAwAgiwEBAAAAAYwBAQAAAAGNAQEAAAABjgEBAAAAAZABAAAAkAECkgEAAACSAQKTAUAAAAABlAFAAAAAAQIAAACoAQAgHAAA6gMAIAMAAACrAQAgHAAA6gMAIB0AAO4DACAMAAAAqwEAIAcAAJgCACAMAACXAgAgFQAA7gMAIIsBAQCTAgAhjAEBAJMCACGNAQEAkwIAIY4BAQCTAgAhkAEAAJQCkAEikgEAAJUCkgEikwFAAJYCACGUAUAAlgIAIQoHAACYAgAgDAAAlwIAIIsBAQCTAgAhjAEBAJMCACGNAQEAkwIAIY4BAQCTAgAhkAEAAJQCkAEikgEAAJUCkgEikwFAAJYCACGUAUAAlgIAIQMAAAADACAcAADmAwAgHQAA8QMAIBEAAAADACADAADYAgAgCAAAmQMAIAsAANoCACAVAADxAwAgiwEBAJMCACGTAUAAlgIAIZQBQACWAgAhowEBAJMCACGkAQEApQIAIaUBAgCkAgAhpgEAANYCACCnAQgAtwIAIagBIADXAgAhqQEIALcCACGqAQIApAIAIasBAQClAgAhDwMAANgCACAIAACZAwAgCwAA2gIAIIsBAQCTAgAhkwFAAJYCACGUAUAAlgIAIaMBAQCTAgAhpAEBAKUCACGlAQIApAIAIaYBAADWAgAgpwEIALcCACGoASAA1wIAIakBCAC3AgAhqgECAKQCACGrAQEApQIAIQMAAAAFACAcAADoAwAgHQAA9AMAIA0AAAAFACAFAAD7AgAgBgAAogMAIBUAAPQDACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbMBAQCTAgAhtAEBAJMCACELBQAA-wIAIAYAAKIDACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGvAQEAkwIAIbABAQClAgAhsQEIALcCACGyAQIA-QIAIbMBAQCTAgAhtAEBAJMCACEKiwEBAAAAAZIBAAAAwQECkwFAAAAAAZQBQAAAAAGxAQgAAAABtAEBAAAAAb8BAQAAAAHBAUAAAAABwgEBAAAAAcMBAQAAAAEPAwAAigMAIAcAAIsDACAIAACaAwAgiwEBAAAAAZMBQAAAAAGUAUAAAAABowEBAAAAAaQBAQAAAAGlAQIAAAABpgEAAIkDACCnAQgAAAABqAEgAAAAAakBCAAAAAGqAQIAAAABqwEBAAAAAQIAAACQAQAgHAAA9gMAIA8GAADOAgAgCgAA7gIAIA0AAM0CACAOAADPAgAgiwEBAAAAAZIBAAAAwQECkwFAAAAAAZQBQAAAAAGxAQgAAAABtAEBAAAAAbYBAQAAAAG_AQEAAAABwQFAAAAAAcIBAQAAAAHDAQEAAAABAgAAAAEAIBwAAPgDACADAAAAAwAgHAAA9gMAIB0AAPwDACARAAAAAwAgAwAA2AIAIAcAANkCACAIAACZAwAgFQAA_AMAIIsBAQCTAgAhkwFAAJYCACGUAUAAlgIAIaMBAQCTAgAhpAEBAKUCACGlAQIApAIAIaYBAADWAgAgpwEIALcCACGoASAA1wIAIakBCAC3AgAhqgECAKQCACGrAQEApQIAIQ8DAADYAgAgBwAA2QIAIAgAAJkDACCLAQEAkwIAIZMBQACWAgAhlAFAAJYCACGjAQEAkwIAIaQBAQClAgAhpQECAKQCACGmAQAA1gIAIKcBCAC3AgAhqAEgANcCACGpAQgAtwIAIaoBAgCkAgAhqwEBAKUCACEDAAAACwAgHAAA-AMAIB0AAP8DACARAAAACwAgBgAAugIAIAoAAOwCACANAAC5AgAgDgAAuwIAIBUAAP8DACCLAQEAkwIAIZIBAAC2AsEBIpMBQACWAgAhlAFAAJYCACGxAQgAtwIAIbQBAQCTAgAhtgEBAJMCACG_AQEAkwIAIcEBQACWAgAhwgEBAJMCACHDAQEApQIAIQ8GAAC6AgAgCgAA7AIAIA0AALkCACAOAAC7AgAgiwEBAJMCACGSAQAAtgLBASKTAUAAlgIAIZQBQACWAgAhsQEIALcCACG0AQEAkwIAIbYBAQCTAgAhvwEBAJMCACHBAUAAlgIAIcIBAQCTAgAhwwEBAKUCACEHiwEBAAAAAZMBQAAAAAGUAUAAAAABtAEBAAAAAbUBAQAAAAG3AQIAAAABuAEBAAAAAQUGAAMKAAINAAQOHAsPHQgEBAAKBxcBCxgIDAQDBQMIBAQACQcPAQgAAgsTCAQEAAcFAAUGAAMHDQECAwkEBAAGAQMKAAEHDgADBgADCQABCgACAwMUAAcVAAsWAAIHGQALGgABCQABAAMGAAMKAAINAAQDBgADCgACDQAEBQQAECIAESMAEiQAEyUAFAAAAAAABQQAECIAESMAEiQAEyUAFAEJAAEBCQABBQQAGSIAGiMAGyQAHCUAHQAAAAAABQQAGSIAGiMAGyQAHCUAHQMGAAMJAAEKAAIDBgADCQABCgACBQQAIiIAIyMAJCQAJSUAJgAAAAAABQQAIiIAIyMAJCQAJSUAJgAAAwQAKyQALCUALQAAAAMEACskACwlAC0CBQAFBgADAgUABQYAAwUEADIiADMjADQkADUlADYAAAAAAAUEADIiADMjADQkADUlADYBCAACAQgAAgUEADsiADwjAD0kAD4lAD8AAAAAAAUEADsiADwjAD0kAD4lAD8AAAMEAEQkAEUlAEYAAAADBABEJABFJQBGEAIBER4BEh8BEyABFCEBFiMBFyUMGCYNGSgBGioMGysOHiwBHy0BIC4MJjEPJzIVKDQLKTULKjcLKzgLLDkLLTsLLj0MLz4WMEALMUIMMkMXM0QLNEULNUYMNkkYN0oeOEsIOUwIOk0IO04IPE8IPVEIPlMMP1QfQFYIQVgMQlkgQ1oIRFsIRVwMRl8hR2AnSGIFSWMFSmYFS2cFTGgFTWoFTmwMT20oUG8FUXEMUnIpU3MFVHQFVXUMVngqV3kuWHoEWXsEWnwEW30EXH4EXYABBF6CAQxfgwEvYIUBBGGHAQxiiAEwY4kBBGSKAQRliwEMZo4BMWePATdokQEDaZIBA2qUAQNrlQEDbJYBA22YAQNumgEMb5sBOHCdAQNxnwEMcqABOXOhAQN0ogEDdaMBDHamATp3pwFAeKkBAnmqAQJ6rQECe64BAnyvAQJ9sQECfrMBDH-0AUGAAbYBAoEBuAEMggG5AUKDAboBAoQBuwEChQG8AQyGAb8BQ4cBwAFH"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("node:buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var UserRole = {
  CUSTOMER: "CUSTOMER",
  TECHNICIAN: "TECHNICIAN",
  ADMIN: "ADMIN"
};
var BookingStatus = {
  REQUESTED: "REQUESTED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  PAID: "PAID",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};
var PaymentStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path2.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/user/user.service.ts
var registerUser = async (payload) => {
  const { name, email, password } = payload;
  const existingUser = await prisma.user.findUnique({ where: { email } });
  if (existingUser) {
    throw new Error("User already exists with this email");
  }
  const hashedPassword = await bcrypt.hash(password, 10);
  const user = await prisma.user.create({
    data: {
      name,
      email,
      password: hashedPassword
    },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    }
  });
  return user;
};
var getUserProfile = async (id) => {
  const user = await prisma.user.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    }
  });
  if (!user) {
    throw new Error("User not found!");
  }
  return user;
};
var userService = { registerUser, getUserProfile };

// src/modules/user/user.controller.ts
var registerUser2 = catchAsync(async (req, res) => {
  const result = await userService.registerUser(req.body);
  sendResponse(res, {
    statusCode: httpStatus.CREATED,
    success: true,
    message: "User registered successfully",
    data: result
  });
});
var getMyProfile = catchAsync(async (req, res) => {
  const { id } = req.user;
  const result = await userService.getUserProfile(id);
  sendResponse(res, {
    statusCode: httpStatus.OK,
    success: true,
    message: "Profile retrieved successfully",
    data: result
  });
});
var userController = { registerUser: registerUser2, getMyProfile };

// src/utils/jwt.ts
import jwt from "jsonwebtoken";
var createToken = (payload, secret, expiresIn) => {
  const token = jwt.sign(
    payload,
    secret,
    {
      expiresIn
    }
  );
  return token;
};
var verifyToken = (token, secret) => {
  try {
    const verifiedToken = jwt.verify(token, secret);
    return {
      success: true,
      data: verifiedToken
    };
  } catch (error) {
    console.log("Token verification failed:", error);
    return {
      success: false,
      error: error.message
    };
  }
};
var jwtUtils = {
  createToken,
  verifyToken
};

// src/middlewares/auth.ts
var auth = (...requiredRoles) => {
  return catchAsync(
    async (req, res, next) => {
      const token = req.cookies.accessToken ? req.cookies.accessToken : req.headers.authorization?.startsWith("Bearer ") ? req.headers.authorization?.split(" ")[1] : req.headers.authorization;
      if (!token) {
        throw new Error("You are not logged in. Please log in to access this resource.");
      }
      const verifiedToken = jwtUtils.verifyToken(token, config_default.jwt_access_secret);
      if (!verifiedToken.success) {
        throw new Error(verifiedToken.error);
      }
      const { email, name, id, role } = verifiedToken.data;
      if (requiredRoles.length && !requiredRoles.includes(role)) {
        throw new Error("Forbidden. You don't have permission to access this resource.");
      }
      const user = await prisma.user.findUnique({
        where: {
          id
          // email,
          // name,
          // role
        }
      });
      if (!user) {
        throw new Error("User not found. Please log in again.");
      }
      if (user.status === "BANNED") {
        throw new Error("Your account has been blocked. Please contact support.");
      }
      req.user = {
        email,
        name,
        id,
        role
      };
      next();
    }
  );
};

// src/modules/user/user.routes.ts
var router = express.Router();
router.post("/register", userController.registerUser);
router.get("/me", auth(), userController.getMyProfile);
var userRoutes = router;

// src/modules/auth/auth.routes.ts
import express2 from "express";

// src/modules/auth/auth.controller.ts
import httpStatus2 from "http-status";

// src/modules/auth/auth.service.ts
import bcrypt2 from "bcryptjs";
var loginUser = async (payload) => {
  const { email, password } = payload;
  const user = await prisma.user.findUnique({ where: { email } });
  if (!user) throw new Error("User not found");
  if (user.status === "BANNED") {
    throw new Error("Your account has been banned.");
  }
  const isPasswordMatched = await bcrypt2.compare(password, user.password);
  if (!isPasswordMatched) throw new Error("Password is incorrect");
  const jwtPayload = { id: user.id, email: user.email, role: user.role };
  const accessToken = jwtUtils.createToken(jwtPayload, config_default.jwt_access_secret, config_default.jwt_access_expires_in);
  const refreshToken3 = jwtUtils.createToken(jwtPayload, config_default.jwt_refresh_secret, config_default.jwt_refresh_expires_in);
  return { accessToken, refreshToken: refreshToken3 };
};
var refreshToken = async (token) => {
  const verifiedRefreshToken = jwtUtils.verifyToken(token, config_default.jwt_refresh_secret);
  if (!verifiedRefreshToken.success) throw new Error(verifiedRefreshToken.error);
  const { id } = verifiedRefreshToken.data;
  const user = await prisma.user.findUniqueOrThrow({ where: { id } });
  if (user.status === "BANNED") throw new Error("User is banned!");
  const jwtPayload = { id, name: user.name, email: user.email, role: user.role };
  const accessToken = jwtUtils.createToken(jwtPayload, config_default.jwt_access_secret, config_default.jwt_access_expires_in);
  return { accessToken };
};
var authService = { loginUser, refreshToken };

// src/modules/auth/auth.controller.ts
var loginUser2 = catchAsync(async (req, res) => {
  const result = await authService.loginUser(req.body);
  const { accessToken, refreshToken: refreshToken3 } = result;
  res.cookie("refreshToken", refreshToken3, {
    secure: config_default.env === "production",
    httpOnly: true,
    maxAge: 7 * 24 * 60 * 60 * 1e3
    // 7 days
  });
  sendResponse(res, {
    statusCode: httpStatus2.OK,
    success: true,
    message: "User logged in successfully",
    data: { accessToken }
  });
});
var refreshToken2 = catchAsync(async (req, res) => {
  const { refreshToken: refreshToken3 } = req.cookies;
  const result = await authService.refreshToken(refreshToken3);
  sendResponse(res, {
    statusCode: httpStatus2.OK,
    success: true,
    message: "Access token refreshed",
    data: result
  });
});
var authController = { loginUser: loginUser2, refreshToken: refreshToken2 };

// src/modules/auth/auth.routes.ts
var router2 = express2.Router();
router2.post("/login", authController.loginUser);
router2.post("/refresh-token", authController.refreshToken);
var authRoutes = router2;

// src/modules/technician/technician.routes.ts
import express3 from "express";

// src/modules/technician/technician.controller.ts
import httpStatus3 from "http-status";

// src/modules/technician/technician.service.ts
var getAllTechnicians = async (filters) => {
  const { location, minRating, skill, searchTerm } = filters;
  const andConditions = [];
  if (location) {
    andConditions.push({
      location: { contains: location, mode: "insensitive" }
    });
  }
  if (minRating) {
    andConditions.push({
      ratingAvg: { gte: parseFloat(minRating) }
    });
  }
  if (skill) {
    andConditions.push({
      skills: { has: skill }
    });
  }
  if (searchTerm) {
    andConditions.push({
      user: {
        name: { contains: searchTerm, mode: "insensitive" }
      }
    });
  }
  const whereConditions = andConditions.length > 0 ? { AND: andConditions } : {};
  const technicians = await prisma.technicianProfile.findMany({
    where: whereConditions,
    include: {
      user: {
        select: { id: true, name: true, email: true, status: true }
      },
      services: true
    },
    orderBy: { ratingAvg: "desc" }
  });
  return technicians;
};
var getTechnicianById = async (id) => {
  const technician = await prisma.technicianProfile.findUniqueOrThrow({
    where: { id },
    include: {
      user: {
        select: { id: true, name: true, email: true, status: true }
      },
      services: {
        include: { category: true }
      }
      // reviews: true  // 👉 Review model বানানোর পর এখানে যোগ করো
    }
  });
  return technician;
};
var updateOwnProfile = async (userId, payload) => {
  const profile = await prisma.technicianProfile.upsert({
    where: { userId },
    update: payload,
    create: {
      userId,
      bio: payload.bio,
      experience: payload.experience ?? 0,
      skills: payload.skills ?? [],
      location: payload.location,
      hourlyRate: payload.hourlyRate ?? 0,
      isAvailable: payload.isAvailable ?? true
    },
    include: {
      user: { select: { id: true, name: true, email: true } }
    }
  });
  return profile;
};
var createOwnService = async (userId, payload) => {
  const profile = await prisma.technicianProfile.findUnique({ where: { userId } });
  if (!profile) {
    throw new Error("Please create your technician profile before adding a service");
  }
  const category = await prisma.category.findUnique({ where: { id: payload.categoryId } });
  if (!category) {
    throw new Error("Invalid category selected");
  }
  const service = await prisma.service.create({
    data: {
      title: payload.title,
      description: payload.description,
      price: payload.price,
      durationMins: payload.durationMins,
      categoryId: payload.categoryId,
      technicianId: profile.id
      // 👈 এখানেই auto-connect হচ্ছে নিজের profile-এর সাথে
    },
    include: {
      category: true
    }
  });
  return service;
};
var getOwnServices = async (userId) => {
  const profile = await prisma.technicianProfile.findUnique({ where: { userId } });
  if (!profile) throw new Error("Technician profile not found");
  const services = await prisma.service.findMany({
    where: { technicianId: profile.id },
    include: { category: true },
    orderBy: { createdAt: "desc" }
  });
  return services;
};
var getOwnBookings = async (userId) => {
  const profile = await prisma.technicianProfile.findUnique({ where: { userId } });
  if (!profile) throw new Error("Technician profile not found");
  const bookings = await prisma.booking.findMany({
    where: { technicianId: profile.id },
    include: {
      service: true,
      customer: { select: { id: true, name: true, email: true } }
    },
    orderBy: { createdAt: "desc" }
  });
  return bookings;
};
var updateBookingStatus = async (userId, bookingId, payload) => {
  const profile = await prisma.technicianProfile.findUnique({ where: { userId } });
  if (!profile) throw new Error("Technician profile not found");
  const booking = await prisma.booking.findUnique({ where: { id: bookingId } });
  if (!booking) throw new Error("Booking not found");
  if (booking.technicianId !== profile.id) {
    throw new Error("You are not authorized to update this booking");
  }
  const { status } = payload;
  const allowedTransitions = {
    REQUESTED: [BookingStatus.ACCEPTED, BookingStatus.DECLINED],
    ACCEPTED: [BookingStatus.IN_PROGRESS],
    DECLINED: [],
    PAID: [BookingStatus.IN_PROGRESS],
    IN_PROGRESS: [BookingStatus.COMPLETED],
    COMPLETED: [],
    CANCELLED: []
  };
  if (!allowedTransitions[booking.status].includes(status)) {
    throw new Error(
      `Cannot change booking status from ${booking.status} to ${status}`
    );
  }
  const updatedBooking = await prisma.booking.update({
    where: { id: bookingId },
    data: { status },
    include: {
      service: true,
      customer: { select: { id: true, name: true, email: true } }
    }
  });
  return updatedBooking;
};
var technicianService = { getAllTechnicians, getTechnicianById, updateOwnProfile, createOwnService, getOwnServices, getOwnBookings, updateBookingStatus };

// src/modules/technician/technician.controller.ts
var getAllTechnicians2 = catchAsync(async (req, res) => {
  const filters = {
    location: req.query.location,
    minRating: req.query.rating,
    skill: req.query.skill,
    searchTerm: req.query.searchTerm
  };
  const result = await technicianService.getAllTechnicians(filters);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Technicians retrieved successfully",
    data: result
  });
});
var getTechnicianById2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await technicianService.getTechnicianById(id);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Technician profile retrieved successfully",
    data: result
  });
});
var updateOwnProfile2 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.updateOwnProfile(userId, req.body);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Technician profile updated successfully",
    data: result
  });
});
var createOwnService2 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.createOwnService(userId, req.body);
  sendResponse(res, {
    statusCode: httpStatus3.CREATED,
    success: true,
    message: "Service created successfully",
    data: result
  });
});
var getOwnServices2 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.getOwnServices(userId);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Your services retrieved successfully",
    data: result
  });
});
var getOwnBookings2 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.getOwnBookings(userId);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Your bookings retrieved successfully",
    data: result
  });
});
var updateBookingStatus2 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const { id } = req.params;
  const result = await technicianService.updateBookingStatus(userId, id, req.body);
  sendResponse(res, {
    statusCode: httpStatus3.OK,
    success: true,
    message: "Booking status updated successfully",
    data: result
  });
});
var technicianController = { getAllTechnicians: getAllTechnicians2, getTechnicianById: getTechnicianById2, getOwnServices: getOwnServices2, createOwnService: createOwnService2, updateOwnProfile: updateOwnProfile2, getOwnBookings: getOwnBookings2, updateBookingStatus: updateBookingStatus2 };

// src/modules/technician/technician.routes.ts
var router3 = express3.Router();
router3.get("/", technicianController.getAllTechnicians);
router3.get("/:id", technicianController.getTechnicianById);
var technicianRoutes = router3;

// src/modules/service/service.routes.ts
import express4 from "express";

// src/modules/service/service.controller.ts
import httpStatus4 from "http-status";

// src/modules/service/service.service.ts
var getAllServices = async (filters) => {
  const { categoryId, location, minRating, searchTerm } = filters;
  const andConditions = [];
  if (categoryId) {
    andConditions.push({ categoryId });
  }
  if (searchTerm) {
    andConditions.push({
      OR: [
        { title: { contains: searchTerm, mode: "insensitive" } },
        { description: { contains: searchTerm, mode: "insensitive" } }
      ]
    });
  }
  if (location) {
    andConditions.push({
      technician: {
        location: { contains: location, mode: "insensitive" }
      }
    });
  }
  if (minRating) {
    andConditions.push({
      technician: {
        ratingAvg: { gte: parseFloat(minRating) }
      }
    });
  }
  const whereConditions = andConditions.length > 0 ? { AND: andConditions } : {};
  const services = await prisma.service.findMany({
    where: whereConditions,
    include: {
      category: true,
      technician: {
        include: {
          user: {
            select: { id: true, name: true, email: true }
          }
        }
      }
    },
    orderBy: { createdAt: "desc" }
  });
  return services;
};
var serviceService = { getAllServices };

// src/modules/service/service.controller.ts
var getAllServices2 = catchAsync(async (req, res) => {
  const filters = {
    categoryId: req.query.type,
    location: req.query.location,
    minRating: req.query.rating,
    searchTerm: req.query.searchTerm
  };
  const result = await serviceService.getAllServices(filters);
  sendResponse(res, {
    statusCode: httpStatus4.OK,
    success: true,
    message: "Services retrieved successfully",
    data: result
  });
});
var serviceController = { getAllServices: getAllServices2 };

// src/modules/service/service.routes.ts
var router4 = express4.Router();
router4.get("/", serviceController.getAllServices);
var serviceRoutes = router4;

// src/modules/category/category.routes.ts
import express5 from "express";

// src/modules/category/category.controller.ts
import httpStatus5 from "http-status";

// src/modules/category/category.service.ts
var getAllCategories = async () => {
  const categories = await prisma.category.findMany({
    orderBy: { name: "asc" }
  });
  return categories;
};
var categoryService = { getAllCategories };

// src/modules/category/category.controller.ts
var getAllCategories2 = catchAsync(async (req, res) => {
  const result = await categoryService.getAllCategories();
  sendResponse(res, {
    statusCode: httpStatus5.OK,
    success: true,
    message: "Categories retrieved successfully",
    data: result
  });
});
var categoryController = { getAllCategories: getAllCategories2 };

// src/modules/category/category.routes.ts
var router5 = express5.Router();
router5.get("/", categoryController.getAllCategories);
var categoryRoutes = router5;

// src/modules/admin/admin.routes.ts
import express6 from "express";

// src/modules/admin/admin.controller.ts
import httpStatus6 from "http-status";

// src/modules/admin/admin.service.ts
var getAllUsers = async () => {
  const users = await prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    },
    orderBy: { createdAt: "desc" }
  });
  return users;
};
var updateUserStatus = async (id, payload) => {
  const user = await prisma.user.findUnique({ where: { id } });
  if (!user) throw new Error("User not found");
  const updatedUser = await prisma.user.update({
    where: { id },
    data: { status: payload.status },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true
    }
  });
  return updatedUser;
};
var getAllCategories3 = async () => {
  const categories = await prisma.category.findMany({
    orderBy: { name: "asc" }
  });
  return categories;
};
var createCategory = async (payload) => {
  const existing = await prisma.category.findUnique({
    where: { name: payload.name }
  });
  if (existing) throw new Error("Category already exists");
  const category = await prisma.category.create({
    data: payload
  });
  return category;
};
var getUserById = async (id) => {
  const user = await prisma.user.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true
    }
  });
  if (!user) throw new Error("User not found");
  return user;
};
var adminService = {
  getAllUsers,
  updateUserStatus,
  getAllCategories: getAllCategories3,
  createCategory,
  getUserById
};

// src/modules/admin/admin.controller.ts
var getAllUsers2 = catchAsync(async (req, res) => {
  const result = await adminService.getAllUsers();
  sendResponse(res, {
    statusCode: httpStatus6.OK,
    success: true,
    message: "Users retrieved successfully",
    data: result
  });
});
var updateUserStatus2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await adminService.updateUserStatus(id, req.body);
  sendResponse(res, {
    statusCode: httpStatus6.OK,
    success: true,
    message: "User status updated successfully",
    data: result
  });
});
var getAllCategories4 = catchAsync(async (req, res) => {
  const result = await adminService.getAllCategories();
  sendResponse(res, {
    statusCode: httpStatus6.OK,
    success: true,
    message: "Categories retrieved successfully",
    data: result
  });
});
var createCategory2 = catchAsync(async (req, res) => {
  const result = await adminService.createCategory(req.body);
  sendResponse(res, {
    statusCode: httpStatus6.CREATED,
    success: true,
    message: "Category created successfully",
    data: result
  });
});
var getUserById2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await adminService.getUserById(id);
  sendResponse(res, {
    statusCode: httpStatus6.OK,
    success: true,
    message: "User retrieved successfully",
    data: result
  });
});
var adminController = {
  getAllUsers: getAllUsers2,
  updateUserStatus: updateUserStatus2,
  getAllCategories: getAllCategories4,
  createCategory: createCategory2,
  getUserById: getUserById2
};

// src/modules/admin/admin.routes.ts
var router6 = express6.Router();
router6.get("/users", auth(UserRole.ADMIN), adminController.getAllUsers);
router6.get("/users/:id", auth(UserRole.ADMIN), adminController.getUserById);
router6.patch("/users/:id", auth(UserRole.ADMIN), adminController.updateUserStatus);
router6.get("/categories", auth(UserRole.ADMIN), adminController.getAllCategories);
router6.post("/categories", auth(UserRole.ADMIN), adminController.createCategory);
var adminRoutes = router6;

// src/modules/booking/booking.routes.ts
import express7 from "express";

// src/modules/booking/booking.controller.ts
import httpStatus7 from "http-status";

// src/modules/booking/booking.service.ts
var createBooking = async (customerId, payload) => {
  const { serviceId, scheduledAt, address, note } = payload;
  const service = await prisma.service.findUnique({ where: { id: serviceId } });
  if (!service) throw new Error("Service not found");
  const booking = await prisma.booking.create({
    data: {
      customerId,
      serviceId,
      technicianId: service.technicianId,
      scheduledAt: new Date(scheduledAt),
      address,
      note,
      price: service.price
    },
    include: {
      service: true,
      technician: {
        include: { user: { select: { id: true, name: true, email: true } } }
      }
    }
  });
  return booking;
};
var getUserBookings = async (userId, role) => {
  const whereConditions = role === UserRole.TECHNICIAN ? { technician: { userId } } : { customerId: userId };
  const bookings = await prisma.booking.findMany({
    where: whereConditions,
    include: {
      service: true,
      customer: { select: { id: true, name: true, email: true } },
      technician: {
        include: { user: { select: { id: true, name: true, email: true } } }
      }
    },
    orderBy: { createdAt: "desc" }
  });
  return bookings;
};
var getBookingById = async (id, userId, role) => {
  const booking = await prisma.booking.findUnique({
    where: { id },
    include: {
      service: true,
      customer: { select: { id: true, name: true, email: true } },
      technician: {
        include: { user: { select: { id: true, name: true, email: true } } }
      }
    }
  });
  if (!booking) throw new Error("Booking not found");
  const isOwner = booking.customerId === userId;
  const isAssignedTechnician = booking.technician.userId === userId;
  const isAdmin = role === UserRole.ADMIN;
  if (!isOwner && !isAssignedTechnician && !isAdmin) {
    throw new Error("You are not authorized to view this booking");
  }
  return booking;
};
var bookingService = { createBooking, getUserBookings, getBookingById };

// src/modules/booking/booking.controller.ts
var createBooking2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const result = await bookingService.createBooking(customerId, req.body);
  sendResponse(res, {
    statusCode: httpStatus7.CREATED,
    success: true,
    message: "Booking created successfully",
    data: result
  });
});
var getUserBookings2 = catchAsync(async (req, res) => {
  const { id: userId, role } = req.user;
  const result = await bookingService.getUserBookings(userId, role);
  sendResponse(res, {
    statusCode: httpStatus7.OK,
    success: true,
    message: "Bookings retrieved successfully",
    data: result
  });
});
var getBookingById2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const { id: userId, role } = req.user;
  const result = await bookingService.getBookingById(id, userId, role);
  sendResponse(res, {
    statusCode: httpStatus7.OK,
    success: true,
    message: "Booking details retrieved successfully",
    data: result
  });
});
var updateOwnProfile3 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.updateOwnProfile(userId, req.body);
  sendResponse(res, {
    statusCode: httpStatus7.OK,
    success: true,
    message: "Technician profile updated successfully",
    data: result
  });
});
var createOwnService3 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.createOwnService(userId, req.body);
  sendResponse(res, {
    statusCode: httpStatus7.CREATED,
    success: true,
    message: "Service created successfully",
    data: result
  });
});
var getOwnServices3 = catchAsync(async (req, res) => {
  const userId = req.user.id;
  const result = await technicianService.getOwnServices(userId);
  sendResponse(res, {
    statusCode: httpStatus7.OK,
    success: true,
    message: "Your services retrieved successfully",
    data: result
  });
});
var bookingController = { createBooking: createBooking2, getUserBookings: getUserBookings2, getBookingById: getBookingById2, getOwnServices: getOwnServices3, createOwnService: createOwnService3, updateOwnProfile: updateOwnProfile3 };

// src/modules/booking/booking.routes.ts
var router7 = express7.Router();
router7.post("/", auth(UserRole.CUSTOMER), bookingController.createBooking);
router7.get("/", auth(UserRole.CUSTOMER, UserRole.TECHNICIAN, UserRole.ADMIN), bookingController.getUserBookings);
router7.get("/:id", auth(UserRole.CUSTOMER, UserRole.TECHNICIAN, UserRole.ADMIN), bookingController.getBookingById);
var bookingRoutes = router7;

// src/modules/technician/technicianSelf.routes.ts
import express8 from "express";
var router8 = express8.Router();
router8.put("/profile", auth(UserRole.TECHNICIAN), technicianController.updateOwnProfile);
router8.post("/services", auth(UserRole.TECHNICIAN), technicianController.createOwnService);
router8.get("/services", auth(UserRole.TECHNICIAN), technicianController.getOwnServices);
router8.get("/bookings", auth(UserRole.TECHNICIAN), technicianController.getOwnBookings);
router8.patch("/bookings/:id", auth(UserRole.TECHNICIAN), technicianController.updateBookingStatus);
var technicianSelfRoutes = router8;

// src/modules/payment/payment.routes.ts
import express9 from "express";

// src/modules/payment/payment.controller.ts
import httpStatus8 from "http-status";

// src/modules/payment/payment.service.ts
import { v4 as uuidv4 } from "uuid";

// src/utils/sslcommerz.ts
import SSLCommerzPayment from "sslcommerz-lts";
var initiateSSLPayment = async (paymentData) => {
  const sslcz = new SSLCommerzPayment(
    config_default.ssl.store_id,
    config_default.ssl.store_passwd,
    config_default.ssl.is_live
  );
  const data = {
    total_amount: paymentData.total_amount,
    currency: "BDT",
    tran_id: paymentData.tran_id,
    success_url: `${config_default.ssl.success_url}?tran_id=${paymentData.tran_id}`,
    fail_url: `${config_default.ssl.fail_url}?tran_id=${paymentData.tran_id}`,
    cancel_url: `${config_default.ssl.cancel_url}?tran_id=${paymentData.tran_id}`,
    ipn_url: config_default.ssl.success_url,
    shipping_method: "NO",
    product_name: "Home Service Booking",
    product_category: "Service",
    product_profile: "general",
    cus_name: paymentData.customerName,
    cus_email: paymentData.customerEmail,
    cus_add1: paymentData.customerAddress,
    cus_city: "Dhaka",
    cus_country: "Bangladesh",
    cus_phone: paymentData.customerPhone,
    ship_name: paymentData.customerName,
    ship_add1: paymentData.customerAddress,
    ship_city: "Dhaka",
    ship_country: "Bangladesh",
    ship_postcode: 1e3
  };
  const apiResponse = await sslcz.init(data);
  return apiResponse;
};

// src/modules/payment/payment.service.ts
var createPayment = async (customerId, payload) => {
  const { bookingId } = payload;
  const booking = await prisma.booking.findUnique({
    where: { id: bookingId },
    include: { customer: true }
  });
  if (!booking) throw new Error("Booking not found");
  if (booking.customerId !== customerId) {
    throw new Error("You are not authorized to pay for this booking");
  }
  if (booking.status !== BookingStatus.ACCEPTED) {
    throw new Error("Booking must be accepted by technician before payment");
  }
  const existingPayment = await prisma.payment.findUnique({ where: { bookingId } });
  if (existingPayment && existingPayment.status === PaymentStatus.COMPLETED) {
    throw new Error("This booking is already paid");
  }
  const tran_id = existingPayment?.transactionId ?? `TXN-${uuidv4()}`;
  const payment = existingPayment ? existingPayment : await prisma.payment.create({
    data: {
      bookingId,
      transactionId: tran_id,
      amount: booking.price,
      status: PaymentStatus.PENDING
    }
  });
  const sslResponse = await initiateSSLPayment({
    total_amount: booking.price,
    tran_id: payment.transactionId,
    customerName: booking.customer.name,
    customerEmail: booking.customer.email,
    customerPhone: "01700000000",
    // schema-তে phone ফিল্ড নেই, চাইলে পরে যোগ করো
    customerAddress: booking.address
  });
  return { paymentUrl: sslResponse.GatewayPageURL, transactionId: payment.transactionId };
};
var confirmPayment = async (tran_id) => {
  const payment = await prisma.payment.findUnique({
    where: { transactionId: tran_id },
    include: { booking: true }
  });
  if (!payment) throw new Error("Payment not found");
  const updatedPayment = await prisma.payment.update({
    where: { transactionId: tran_id },
    data: { status: PaymentStatus.COMPLETED, paidAt: /* @__PURE__ */ new Date() }
  });
  await prisma.booking.update({
    where: { id: payment.bookingId },
    data: { status: BookingStatus.PAID }
  });
  return updatedPayment;
};
var failPayment = async (tran_id) => {
  const payment = await prisma.payment.update({
    where: { transactionId: tran_id },
    data: { status: PaymentStatus.FAILED }
  });
  return payment;
};
var getUserPayments = async (customerId) => {
  const payments = await prisma.payment.findMany({
    where: { booking: { customerId } },
    include: { booking: { include: { service: true } } },
    orderBy: { createdAt: "desc" }
  });
  return payments;
};
var getPaymentById = async (id, customerId) => {
  const payment = await prisma.payment.findUnique({
    where: { id },
    include: { booking: { include: { service: true } } }
  });
  if (!payment) throw new Error("Payment not found");
  if (payment.booking.customerId !== customerId) {
    throw new Error("You are not authorized to view this payment");
  }
  return payment;
};
var paymentService = {
  createPayment,
  confirmPayment,
  failPayment,
  getUserPayments,
  getPaymentById
};

// src/modules/payment/payment.controller.ts
var createPayment2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const result = await paymentService.createPayment(customerId, req.body);
  sendResponse(res, {
    statusCode: httpStatus8.OK,
    success: true,
    message: "Payment session created successfully",
    data: result
  });
});
var confirmPayment2 = catchAsync(async (req, res) => {
  const tran_id = req.query.tran_id || req.body.tran_id;
  await paymentService.confirmPayment(tran_id);
  return res.redirect(`${config_default.frontend_url}/payment/success?tran_id=${tran_id}`);
});
var failPayment2 = catchAsync(async (req, res) => {
  const tran_id = req.query.tran_id || req.body.tran_id;
  await paymentService.failPayment(tran_id);
  return res.redirect(`${config_default.frontend_url}/payment/fail?tran_id=${tran_id}`);
});
var cancelPayment = catchAsync(async (req, res) => {
  const tran_id = req.query.tran_id || req.body.tran_id;
  await paymentService.failPayment(tran_id);
  return res.redirect(`${config_default.frontend_url}/payment/cancel?tran_id=${tran_id}`);
});
var getUserPayments2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const result = await paymentService.getUserPayments(customerId);
  sendResponse(res, {
    statusCode: httpStatus8.OK,
    success: true,
    message: "Payments retrieved successfully",
    data: result
  });
});
var getPaymentById2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const { id } = req.params;
  const result = await paymentService.getPaymentById(id, customerId);
  sendResponse(res, {
    statusCode: httpStatus8.OK,
    success: true,
    message: "Payment details retrieved successfully",
    data: result
  });
});
var paymentController = {
  createPayment: createPayment2,
  confirmPayment: confirmPayment2,
  failPayment: failPayment2,
  cancelPayment,
  getUserPayments: getUserPayments2,
  getPaymentById: getPaymentById2
};

// src/modules/payment/payment.routes.ts
var router9 = express9.Router();
router9.post("/create", auth(UserRole.CUSTOMER), paymentController.createPayment);
router9.post("/confirm", paymentController.confirmPayment);
router9.get("/confirm", paymentController.confirmPayment);
router9.post("/fail", paymentController.failPayment);
router9.post("/cancel", paymentController.cancelPayment);
router9.get("/", auth(UserRole.CUSTOMER), paymentController.getUserPayments);
router9.get("/:id", auth(UserRole.CUSTOMER), paymentController.getPaymentById);
var paymentRoutes = router9;

// src/modules/review/review.route.ts
import express10 from "express";

// src/modules/review/review.controller.ts
import httpStatus9 from "http-status";

// src/modules/review/review.service.ts
var createReview = async (customerId, payload) => {
  const { bookingId, rating, comment } = payload;
  if (rating < 1 || rating > 5) {
    throw new Error("Rating must be between 1 and 5");
  }
  const booking = await prisma.booking.findUnique({ where: { id: bookingId } });
  if (!booking) throw new Error("Booking not found");
  if (booking.customerId !== customerId) {
    throw new Error("You are not authorized to review this booking");
  }
  if (booking.status !== BookingStatus.COMPLETED) {
    throw new Error("You can only review a completed booking");
  }
  const existingReview = await prisma.review.findUnique({ where: { bookingId } });
  if (existingReview) {
    throw new Error("You have already reviewed this booking");
  }
  const review = await prisma.review.create({
    data: {
      bookingId,
      customerId,
      technicianId: booking.technicianId,
      rating,
      comment
    },
    include: {
      customer: { select: { id: true, name: true } },
      booking: { include: { service: true } }
    }
  });
  const aggregate = await prisma.review.aggregate({
    where: { technicianId: booking.technicianId },
    _avg: { rating: true },
    _count: { rating: true }
  });
  await prisma.technicianProfile.update({
    where: { id: booking.technicianId },
    data: {
      ratingAvg: aggregate._avg.rating ?? 0,
      totalReviews: aggregate._count.rating
    }
  });
  return review;
};
var getMyReviews = async (customerId) => {
  const reviews = await prisma.review.findMany({
    where: { customerId },
    include: {
      booking: { include: { service: true } },
      technician: { include: { user: { select: { id: true, name: true } } } }
    },
    orderBy: { createdAt: "desc" }
  });
  return reviews;
};
var getTechnicianReviews = async (technicianId) => {
  const reviews = await prisma.review.findMany({
    where: { technicianId },
    include: {
      customer: { select: { id: true, name: true } },
      booking: { include: { service: true } }
    },
    orderBy: { createdAt: "desc" }
  });
  return reviews;
};
var reviewService = { createReview, getMyReviews, getTechnicianReviews };

// src/modules/review/review.controller.ts
var createReview2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const result = await reviewService.createReview(customerId, req.body);
  sendResponse(res, {
    statusCode: httpStatus9.CREATED,
    success: true,
    message: "Review submitted successfully",
    data: result
  });
});
var getMyReviews2 = catchAsync(async (req, res) => {
  const customerId = req.user.id;
  const result = await reviewService.getMyReviews(customerId);
  sendResponse(res, {
    statusCode: httpStatus9.OK,
    success: true,
    message: "Your reviews retrieved successfully",
    data: result
  });
});
var getTechnicianReviews2 = catchAsync(async (req, res) => {
  const { technicianId } = req.params;
  const result = await reviewService.getTechnicianReviews(technicianId);
  sendResponse(res, {
    statusCode: httpStatus9.OK,
    success: true,
    message: "Technician reviews retrieved successfully",
    data: result
  });
});
var reviewController = { createReview: createReview2, getMyReviews: getMyReviews2, getTechnicianReviews: getTechnicianReviews2 };

// src/modules/review/review.route.ts
var router10 = express10.Router();
router10.post("/", auth(UserRole.CUSTOMER), reviewController.createReview);
router10.get("/my-reviews", auth(UserRole.CUSTOMER), reviewController.getMyReviews);
router10.get("/technician/:technicianId", reviewController.getTechnicianReviews);
var reviewRoutes = router10;

// src/app.ts
var app = express11();
app.use(cors({
  origin: config_default.app_url,
  credentials: true
}));
app.use(express11.json());
app.use(express11.urlencoded({ extended: true }));
app.use(cookieParser());
app.get("/", (req, res) => {
  res.send("Hello, World!");
});
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/services", serviceRoutes);
app.use("/api/technicians", technicianRoutes);
app.use("/api/technician", technicianSelfRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/bookings", bookingRoutes);
app.use("/api/payments", paymentRoutes);
app.use("/api/reviews", reviewRoutes);
var app_default = app;

// api-entry.ts
var api_entry_default = app_default;
export {
  api_entry_default as default
};
